assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017d3be04ba2970c-pi
  filename: image_784682.jpg
  alt_text: validation_key
  title: validation_key
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0177448f7241970d-pi
  filename: image_298014.jpg
  alt_text: validation_key
  title: validation_key
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017d3be04c23970c-pi
  filename: image_830434.jpg
  alt_text: validation_key
  title: validation_key
  asset_type: image
