assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0177437cfeab970d-pi
  filename: image_621205.jpg
  alt_text: new_product
  title: new_product
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0177437cff1e970d-pi
  filename: image_744908.jpg
  alt_text: new_product
  title: new_product
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b016768a1d925970b-pi
  filename: image_883556.jpg
  alt_text: new_product
  title: new_product
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01761696cf4e970c-pi
  filename: image_656516.jpg
  alt_text: new_product
  title: new_product
  asset_type: image
