assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b019b03bf53d2970c-pi
  filename: image_107997.jpg
  alt_text: acad
  title: acad
  asset_type: image
- url: http://adndevblog.typepad.com/adn-pipe-demo-2.zip
  filename: adn-pipe-demo-2.zip
  alt_text: ADN Pipe Demo.zip
  title: ADN Pipe Demo.zip
  asset_type: file
