assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017c38562a7b970b-450wi
  filename: image_331888.jpg
  alt_text: RDWG_missing_policies
  title: RDWG_missing_policies
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017d42854588970c-450wi
  filename: image_977519.jpg
  alt_text: RDWG_missing_policies
  title: RDWG_missing_policies
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017ee9f987e9970d-450wi
  filename: image_553209.jpg
  alt_text: RDWG_missing_policies
  title: RDWG_missing_policies
  asset_type: image
