assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c814e3cd970b-320wi
  filename: image_524478.jpg
  alt_text: DisplayPlotBubble
  title: DisplayPlotBubble
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c814e3f5970b-500wi
  filename: image_980576.jpg
  alt_text: DisplayPlotBubble
  title: DisplayPlotBubble
  asset_type: image
