assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0263e98f4336200b-pi
  filename: image_733671.jpg
  alt_text: ''
  title: ''
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02788014750d200d-pi
  filename: image_153569.jpg
  alt_text: ''
  title: ''
  asset_type: image
