assets:
- url: https://justonesandzeros.typepad.com/images/TipsAndTricks2.png
  filename: TipsAndTricks2.png
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/images/2011/LoadTester.png
  filename: LoadTester.png
  alt_text: ''
  title: ''
  asset_type: image
- url: http://justonesandzeros.typepad.com/Apps/TestLoader/TestLoader-2012.zip
  filename: TestLoader-2012.zip
  alt_text: Click here to download the utility
  title: Click here to download the utility
  asset_type: file
