assets:
- url: https://justonesandzeros.typepad.com/images/Concepts3.png
  filename: Concepts3.png
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/images/2012/CustomEntities/ConfigureCustomObjectDefs.png
  filename: ConfigureCustomObjectDefs.png
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/images/2012/CustomEntities/CustomObjectDef.png
  filename: CustomObjectDef.png
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/images/2012/CustomEntities/Ve1.png
  filename: Ve1.png
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/images/2012/CustomEntities/NewFoo.png
  filename: NewFoo.png
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/images/2012/CustomEntities/UDP.png
  filename: UDP.png
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/images/2012/CustomEntities/CatConfig.png
  filename: CatConfig.png
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/images/2012/CustomEntities/CatRules.png
  filename: CatRules.png
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/images/2012/CustomEntities/Ve2.png
  filename: Ve2.png
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/images/Concepts3-1.png
  filename: Concepts3-1.png
  alt_text: ''
  title: ''
  asset_type: image
