assets:
- url: https://justonesandzeros.typepad.com/images/Vault4.png
  filename: Vault4.png
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/images/SampleApp4.png
  filename: SampleApp4.png
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/JeffreyFishman.jpg
  filename: JeffreyFishman.jpg
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/images/2020/EffectivePermissions/EffectivePermissionsLocation.png
  filename: EffectivePermissionsLocation.png
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/images/2020/EffectivePermissions/EffectivePermissionsOverview.png
  filename: EffectivePermissionsOverview.png
  alt_text: ''
  title: ''
  asset_type: image
- url: https://justonesandzeros.typepad.com/Apps/EffectiveFolderPermissions/effectivePermissions-6.0.0.0-bin.zip
  filename: effectivePermissions-6.0.0.0-bin.zip
  alt_text: Click here to download the application
  title: Click here to download the application
  asset_type: file
- url: https://justonesandzeros.typepad.com/Apps/EffectiveFolderPermissions/effectivePermissions-6.0.0.0-src.zip
  filename: effectivePermissions-6.0.0.0-src.zip
  alt_text: Click here to download the source code
  title: Click here to download the source code
  asset_type: file
