assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017eea635f7a970d-250wi
  filename: image_e686b0.jpg
  alt_text: Upload from desktop to cloud and view on mobile device
  title: Upload from desktop to cloud and view on mobile device
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017d42ef1dda970c-250wi
  filename: image_de2a16.jpg
  alt_text: Edit on mobile device, update data repository and BIM
  title: Edit on mobile device, update data repository and BIM
  asset_type: image
