assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017ee8a74f3f970d-pi
  filename: image_c22895.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017d41336602970c-pi
  filename: image_547a7e.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017c37041664970b-pi
  filename: image_c2cb28.jpg
  alt_text: image
  title: image
  asset_type: image
- url: http://adndevblog.typepad.com/cloud_and_mobile/WCFWithSSL_2.zip
  filename: WCFWithSSL_2.zip
  alt_text: here
  title: here
  asset_type: file
