assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb0871d0b9970d-pi
  filename: image_3a0f3a.jpg
  alt_text: Screen Shot 2015-09-14 at 3.47.34 PM
  title: Screen Shot 2015-09-14 at 3.47.34 PM
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb0871d0c1970d-pi
  filename: image_0b44a1.jpg
  alt_text: '992012145'
  title: '992012145'
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb0871d0c5970d-pi
  filename: image_1f92e0.jpg
  alt_text: Smile
  title: ''
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d15763bb970c-pi
  filename: image_eb15db.jpg
  alt_text: Screen Shot 2015-09-14 at 4.26.36 PM
  title: Screen Shot 2015-09-14 at 4.26.36 PM
  asset_type: image
