assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb09249f5c970d-800wi
  filename: image_9b4e32.jpg
  alt_text: Screen Shot 2016-07-29 at 19.10.07
  title: Screen Shot 2016-07-29 at 19.10.07
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c8812283970b-500wi
  filename: image_a42a3f.jpg
  alt_text: Screen Shot 2016-07-29 at 19.23.19
  title: Screen Shot 2016-07-29 at 19.23.19
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c8813e16970b-500wi
  filename: image_416b33.jpg
  alt_text: Screen Shot 2016-07-30 at 00.35.28
  title: Screen Shot 2016-07-30 at 00.35.28
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c881415d970b-500wi
  filename: image_28f630.jpg
  alt_text: Screen Shot 2016-07-30 at 01.27.11
  title: Screen Shot 2016-07-30 at 01.27.11
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb09249e61970d-800wi
  filename: image_1e6346.jpg
  alt_text: '20160727101631'
  title: '20160727101631'
  asset_type: image
