assets:
- url: http://adndevblog.typepad.com/automationdemo-vb.net-1.zip
  filename: automationdemo-vb.net-1.zip
  alt_text: AutomationDemo VB.Net.zip
  title: AutomationDemo VB.Net.zip
  asset_type: file
