assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017c3820db37970b-450wi
  filename: image_767307.jpg
  alt_text: AllowCustomValuesSetting
  title: AllowCustomValuesSetting
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017d4250018e970c-450wi
  filename: image_0f8c6e.jpg
  alt_text: AllowCustomValue
  title: AllowCustomValue
  asset_type: image
