assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b019aff8fc8ae970b-450wi
  filename: image_1c5612.jpg
  alt_text: Assemblyproperties
  title: Assemblyproperties
  asset_type: image
- url: http://adndevblog.typepad.com/files/mixedmanagedutils_2013-09-23.zip
  filename: mixedmanagedutils_2013-09-23.zip
  alt_text: Download MixedManagedUtils_2013-09-23
  title: Download MixedManagedUtils_2013-09-23
  asset_type: file
