assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b019b03c03cc0970d-pi
  filename: image_acb9b5.jpg
  alt_text: inventor
  title: inventor
  asset_type: image
- url: http://adndevblog.typepad.com/adn-pipe-demo-4.zip
  filename: adn-pipe-demo-4.zip
  alt_text: ADN Pipe Demo.zip
  title: ADN Pipe Demo.zip
  asset_type: file
