assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01a73d8e4d20970d-450wi
  filename: image_b37a46.jpg
  alt_text: C360_config
  title: C360_config
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01a73d9a5980970d-450wi
  filename: image_1da972.jpg
  alt_text: ConfigSettings
  title: ConfigSettings
  asset_type: image
