assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d19fe105970c-500wi
  filename: image_5aef7e.jpg
  alt_text: Params2
  title: Params2
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb08ba8d7d970d-500wi
  filename: image_395c7e.jpg
  alt_text: Params3
  title: Params3
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d19fe221970c-500wi
  filename: image_1837c0.jpg
  alt_text: Params1
  title: Params1
  asset_type: image
