assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c819ae25970b-500wi
  filename: image_79b8cd.jpg
  alt_text: ApprenticeMultiThread
  title: ApprenticeMultiThread
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c819af47970b-500wi
  filename: image_7f71b8.jpg
  alt_text: SolutionDir
  title: SolutionDir
  asset_type: image
