comments:
- author: Rudolf Honke
  email: rudolf.honke@acadGraph.de
  ip: 193.158.119.50
  url: http://www.acadGraph.de
  date: '2012-09-24 04:34:39'
  body: 'Hi Saikat,


    Name property may be not unique since two rooms could have the same name.


    Also, toroom and fromroom properties are not reliable  in some cases.


    <a href="http://thebuildingcoder.typepad.com/blog/2011/03/unreliable-room-properties.html">http://thebuildingcoder.typepad.com/blog/2011/03/unreliable-room-properties.html</a>


    Best regards,

    Rudolf


    -----'
