comments:
- author: Mallikarjuna
  email: dmallikarjuna@live.in
  ip: 122.170.103.215
  url: ''
  date: '2012-10-20 00:50:20'
  body: 'Dear Xiaodong Liang,


    I want to add image or icon in Revit 3D view through programmatically in C#.net


    Please help me.


    Thankyou,

    Mallikarjuna'
- author: Jeremy Tammik
  email: ''
  ip: 87.146.183.197
  url: http://profile.typepad.com/jeremytammik
  date: '2012-10-22 09:36:57'
  body: 'Dear Mallikarjuna,


    I see that you asked the same question in five different places, to me, Saikat,
    Mikako, and Xiaodong.


    That is a bit much, really. Please avoid that in the future.


    Anyway, as Saikat said:


    It does not seem possible to add an image in a 3D view in Revit using the Revit
    User Interface itself. The image button appears disabled when the active view
    is a 3D view. Therefore, it is probably not possible to insert an image in a 3D
    view using the API either. If the UI does not support it, in most cases, the API
    does not either.


    Cheers, Jeremy.

    -----'
