comments:
- author: Paul Hildebrandt
  email: kfpopeye@yahoo.com
  ip: 50.98.232.76
  url: ''
  date: '2013-08-25 15:31:36'
  body: I am having trouble getting the localization to work. I created an app that
    displays a resource string in a messagebox but when I use the tag German in the
    addin file the english text keeps appearing instead of the German text.
- author: Paul Hildebrandt
  email: kfpopeye@yahoo.com
  ip: 50.98.232.76
  url: ''
  date: '2013-08-25 15:33:12'
  body: Part of my message got removed because of HTML tags. I use the languagetype
    tag to force Revit to use German.
- author: Paul Hildebrandt
  email: kfpopeye@yahoo.com
  ip: 50.98.232.76
  url: ''
  date: '2013-08-25 17:01:38'
  body: 'Never mind, I found the answer. The issue is with my version of Windows.
    Apparently, Windows 7 Premium and Professional only support having 1 language
    installed at any given time.


    In order to test my apps in another language I would have to install a German
    version of Windows first. Only Windows Ultimate and Enterprise allow you to have
    more than one language on your computer.'
- author: Augusto Goncalves
  email: ''
  ip: 177.84.160.215
  url: http://profile.typepad.com/6p0168e7e7c9dd970c
  date: '2013-09-12 06:40:35'
  body: 'Or under computer settings (Control Panel), you can change the Localization
    settings, which should affect which resource is loaded.


    Regards,

    Augusto Goncalves

    -----'
