comments:
- author: Babu
  email: babu.rajan@hyderconsulting.com
  ip: 203.191.193.194
  url: ''
  date: '2014-09-03 17:48:52'
  body: 'Hi Jaime,

    Thanks for your solution with sample code.

    Will you please explain how to get the value form Settings

    <a href="http://msdn.microsoft.com/en-us/library/aa730869(v=vs.80).aspx">http://msdn.microsoft.com/en-us/library/aa730869(v=vs.80).aspx</a>


    with the settings you can have string, integer etc


    Regards


    Babu'
- author: Jaime Rosales
  email: ''
  ip: 132.188.64.149
  url: http://profile.typepad.com/6p01a3fd2cdec5970b
  date: '2014-09-04 06:58:30'
  body: 'Hi Babu,


    I was about to start explaining this, when I ran into this amazing post explaining
    all the questions you may have regarding the use of Settings or AppSettings. Hope
    it helps.


    "All the configuration setting values are stored in string format in the appSettings
    section of an application''s configuration file."


    "But it gets a little more complex if you need to grab a value that''s not a string.
    For numeric or enum values you need to first ensure the value exists (is non-null)
    and then convert the string explicitly to whatever type, since configuration values
    are always strings."


    <a href="http://weblog.west-wind.com/posts/2012/Dec/28/Building-a-better-NET-Application-Configuration-Class-revisited">http://weblog.west-wind.com/posts/2012/Dec/28/Building-a-better-NET-Application-Configuration-Class-revisited</a>


    Cheers,

    Jaime

    -----'
