comments:
- author: R.P.R.
  email: ''
  ip: 189.166.223.55
  url: http://profile.typepad.com/6p01b7c95e1406970b
  date: '2018-04-04 22:04:11'
  body: 'Thanks for your recommendations, really helpful. I also want to recommend
    this program to make your own Wordpress plugins I recently tried for , is awesome:

    <a href="https://bit.ly/2GW7m5a">https://bit.ly/2GW7m5a</a>


    -----'
