comments:
- author: Technostruct LLC
  email: technostructllc@gmail.com
  ip: 117.97.155.72
  url: http://technostruct.com/blog/advantages-of-3d-drawings-in-mechanical-design-technostruct/
  date: '2018-11-29 04:20:03'
  body: Thanks for writing such an informative blog.
- author: SS Groupe
  email: popalexandra88@yahoo.com
  ip: 188.27.131.29
  url: https://ssgroupe.ca/
  date: '2023-03-15 03:42:27'
  body: 'Not bad. Can''t wait to see this type of API implemented in more machines.

    -----'
