assets:
- url: http://modthemachine.typepad.com/SW2InventorGuideV1.pdf
  filename: SW2InventorGuideV1.pdf
  alt_text: Migrating SolidWorks Applications to Autodesk Inventor
  title: Migrating SolidWorks Applications to Autodesk Inventor
  asset_type: file
