assets:
- url: https://modthemachine.typepad.com/.a/6a00e553fcbfc68834017ee410921f970d-pi
  filename: image_380451.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://modthemachine.typepad.com/.a/6a00e553fcbfc68834017d3c9b3995970c-pi
  filename: image_669255.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://modthemachine.typepad.com/.a/6a00e553fcbfc68834017c326cc49b970b-pi
  filename: image_705981.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://modthemachine.typepad.com/.a/6a00e553fcbfc68834017d3c9b39b0970c-pi
  filename: image_525036.jpg
  alt_text: image
  title: image
  asset_type: image
