assets:
- url: https://modthemachine.typepad.com/.a/6a00e553fcbfc688340191042b8527970c-pi
  filename: image_369132.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://modthemachine.typepad.com/.a/6a00e553fcbfc688340192abf48fc6970d-pi
  filename: image_109999.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://modthemachine.typepad.com/.a/6a00e553fcbfc6883401901e34ff77970b-pi
  filename: image_841077.jpg
  alt_text: image
  title: image
  asset_type: image
