assets:
- url: https://modthemachine.typepad.com/.a/6a00e553fcbfc688340278801cc2a6200d-500wi
  filename: image_464325.jpg
  alt_text: 2021-03-18_17-50-47 (3)
  title: 2021-03-18_17-50-47 (3)
  asset_type: image
- url: https://modthemachine.typepad.com/.a/6a00e553fcbfc68834026bdec5009e200c-500wi
  filename: image_388557.jpg
  alt_text: 2021-03-18_17-50-47 (3)
  title: 2021-03-18_17-50-47 (3)
  asset_type: image
