assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201157098ffaf970b-pi
  filename: image_733256.jpg
  alt_text: Result of driving AutoCAD via in- and out-of-proc code
  title: Result of driving AutoCAD via in- and out-of-proc code
  asset_type: image
