assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201156faf9386970c-pi
  filename: image_260615.jpg
  alt_text: Result of driving AutoCAD via in- and out-of-proc code (redux)
  title: Result of driving AutoCAD via in- and out-of-proc code (redux)
  asset_type: image
