assets:
- url: http://download.autodesk.com/media/adn/ACAD_Using_WPF_in_your_applications_02June2009.zip
  filename: ACAD_Using_WPF_in_your_applications_02June2009.zip
  alt_text: recorded
  title: recorded
  asset_type: file
