assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20120a8d6eb55970b-pi
  filename: image_735708.jpg
  alt_text: Exception after installing AutoCAD 2010 Update 1
  title: Exception after installing AutoCAD 2010 Update 1
  asset_type: image
- url: http://through-the-interface.typepad.com/files/drivingautocad.zip
  filename: drivingautocad.zip
  alt_text: the source project
  title: the source project
  asset_type: file
