assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20134890113b6970c-pi
  filename: image_105363.jpg
  alt_text: Component architecture
  title: Component architecture
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20134890113ed970c-pi
  filename: image_461086.jpg
  alt_text: Component architecture
  title: Component architecture
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201348901140c970c-pi
  filename: image_792256.jpg
  alt_text: Component architecture
  title: Component architecture
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20133f5e0ec75970b-pi
  filename: image_975765.jpg
  alt_text: Component architecture
  title: Component architecture
  asset_type: image
- url: http://through-the-interface.typepad.com/files/BrowsePhotosynth-for-AU.zip
  filename: BrowsePhotosynth-for-AU.zip
  alt_text: here for download
  title: here for download
  asset_type: file
- url: http://through-the-interface.typepad.com/files/BrowsePhotosynth-for-AU.zip
  filename: BrowsePhotosynth-for-AU.zip
  alt_text: here for download
  title: here for download
  asset_type: file
