assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20133eca8a158970b-pi
  filename: image_45858.jpg
  alt_text: Quick Access Toolbar icon added
  title: Quick Access Toolbar icon added
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201347fd88bda970c-pi
  filename: image_313714.jpg
  alt_text: Quick Access Toolbar icon added
  title: Quick Access Toolbar icon added
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201347fd88c25970c-pi
  filename: image_702788.jpg
  alt_text: Quick Access Toolbar icon added
  title: Quick Access Toolbar icon added
  asset_type: image
