assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e5fcabb55970c-pi
  filename: image_411210.jpg
  alt_text: Getting to the settings on Vista
  title: Getting to the settings on Vista
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20147e325b2be970b-pi
  filename: image_594912.jpg
  alt_text: Getting to the settings on Vista
  title: Getting to the settings on Vista
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e86a5b866970d-pi
  filename: image_198495.jpg
  alt_text: Getting to the settings on Vista
  title: Getting to the settings on Vista
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e86a5b881970d-pi
  filename: image_21010.jpg
  alt_text: Getting to the settings on Vista
  title: Getting to the settings on Vista
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e86a5b89c970d-pi
  filename: image_398573.jpg
  alt_text: Getting to the settings on Vista
  title: Getting to the settings on Vista
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20147e325b357970b-pi
  filename: image_94133.jpg
  alt_text: Getting to the settings on Vista
  title: Getting to the settings on Vista
  asset_type: image
