assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e8b478037970d-pi
  filename: image_721974.jpg
  alt_text: Downloading Spiro from Autodesk Exchange
  title: Downloading Spiro from Autodesk Exchange
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20154352731b9970c-pi
  filename: image_466480.jpg
  alt_text: Downloading Spiro from Autodesk Exchange
  title: Downloading Spiro from Autodesk Exchange
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20154352731d5970c-pi
  filename: image_645323.jpg
  alt_text: Downloading Spiro from Autodesk Exchange
  title: Downloading Spiro from Autodesk Exchange
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e8b478087970d-pi
  filename: image_986308.jpg
  alt_text: Downloading Spiro from Autodesk Exchange
  title: Downloading Spiro from Autodesk Exchange
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e8b479005970d-pi
  filename: image_922944.jpg
  alt_text: Downloading Spiro from Autodesk Exchange
  title: Downloading Spiro from Autodesk Exchange
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201539153c345970b-pi
  filename: image_828626.jpg
  alt_text: Downloading Spiro from Autodesk Exchange
  title: Downloading Spiro from Autodesk Exchange
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e8b479574970d-pi
  filename: image_956861.jpg
  alt_text: Downloading Spiro from Autodesk Exchange
  title: Downloading Spiro from Autodesk Exchange
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e8b47903d970d-pi
  filename: image_509411.jpg
  alt_text: Downloading Spiro from Autodesk Exchange
  title: Downloading Spiro from Autodesk Exchange
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20154352740ef970c-pi
  filename: image_966670.jpg
  alt_text: Downloading Spiro from Autodesk Exchange
  title: Downloading Spiro from Autodesk Exchange
  asset_type: image
