assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2015391657d9c970b-pi
  filename: image_968402.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201543538e6c1970c-pi
  filename: image_107124.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201543538e6d3970c-pi
  filename: image_222981.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e8b5927b0970d-pi
  filename: image_204171.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e8b5927bf970d-pi
  filename: image_684127.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e8b592817970d-pi
  filename: image_206203.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e8b59286b970d-pi
  filename: image_558132.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2015391657e40970b-pi
  filename: image_539947.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e8b5928a3970d-pi
  filename: image_848810.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e8b5928c6970d-pi
  filename: image_653738.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2015391657e88970b-pi
  filename: image_924958.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201543538e7f6970c-pi
  filename: image_466931.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201543538e80c970c-pi
  filename: image_334506.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2015391657ee7970b-pi
  filename: image_628508.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201543538e880970c-pi
  filename: image_493996.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2014e8b59295a970d-pi
  filename: image_15314.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2015391657f0f970b-pi
  filename: image_456329.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2015391657f1a970b-pi
  filename: image_584667.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2015391657f23970b-pi
  filename: image_730234.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2015391657f66970b-pi
  filename: image_594781.jpg
  alt_text: Sign in with your Autodesk ID
  title: Sign in with your Autodesk ID
  asset_type: image
