assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017ee55eb55d970d-pi
  filename: image_577976.jpg
  alt_text: MRU Extractor in the Core Console
  title: MRU Extractor in the Core Console
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017d3de9adae970c-pi
  filename: image_738394.jpg
  alt_text: MRU Extractor in the Core Console
  title: MRU Extractor in the Core Console
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017d3de9adfe970c-pi
  filename: image_266716.jpg
  alt_text: MRU Extractor in the Core Console
  title: MRU Extractor in the Core Console
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017ee55eb62b970d-pi
  filename: image_644223.jpg
  alt_text: MRU Extractor in the Core Console
  title: MRU Extractor in the Core Console
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017ee55eb670970d-pi
  filename: image_53470.jpg
  alt_text: MRU Extractor in the Core Console
  title: MRU Extractor in the Core Console
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017ee55eb69f970d-pi
  filename: image_925486.jpg
  alt_text: MRU Extractor in the Core Console
  title: MRU Extractor in the Core Console
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017ee55eb6fd970d-pi
  filename: image_382098.jpg
  alt_text: MRU Extractor in the Core Console
  title: MRU Extractor in the Core Console
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017ee55eb732970d-pi
  filename: image_512469.jpg
  alt_text: MRU Extractor in the Core Console
  title: MRU Extractor in the Core Console
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017d3de9aeeb970c-pi
  filename: image_137959.jpg
  alt_text: MRU Extractor in the Core Console
  title: MRU Extractor in the Core Console
  asset_type: image
- url: http://through-the-interface.typepad.com/files/MetroCAD-4.zip
  filename: MetroCAD-4.zip
  alt_text: Here’s the accompanying source project for the MetroCAD application
  title: Here’s the accompanying source project for the MetroCAD application
  asset_type: file
