assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017c3391f9f5970b-pi
  filename: image_172979.jpg
  alt_text: Windows 8 Start screen
  title: Windows 8 Start screen
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017ee535589b970d-pi
  filename: image_697208.jpg
  alt_text: Windows 8 Start screen
  title: Windows 8 Start screen
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017d3dc05fb9970c-pi
  filename: image_213828.jpg
  alt_text: Windows 8 Start screen
  title: Windows 8 Start screen
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017d3dc05fe8970c-pi
  filename: image_482882.jpg
  alt_text: Windows 8 Start screen
  title: Windows 8 Start screen
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017c3391fa92970b-pi
  filename: image_158073.jpg
  alt_text: Windows 8 Start screen
  title: Windows 8 Start screen
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017ee5355957970d-pi
  filename: image_537720.jpg
  alt_text: Windows 8 Start screen
  title: Windows 8 Start screen
  asset_type: image
- url: http://download.microsoft.com/download/4/2/1/4213D2B3-FB36-4969-BFEF-19C926C4BBDE/SHAPE12_9.pptx
  filename: SHAPE12_9.pptx
  alt_text: presentations
  title: presentations
  asset_type: file
