assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017c329f67da970b-pi
  filename: image_357315.jpg
  alt_text: My Parallels Machine List
  title: My Parallels Machine List
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017d3ccdf252970c-pi
  filename: image_673351.jpg
  alt_text: My Parallels Machine List
  title: My Parallels Machine List
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017ee443487f970d-pi
  filename: image_114514.jpg
  alt_text: My Parallels Machine List
  title: My Parallels Machine List
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017c329f6881970b-pi
  filename: image_525480.jpg
  alt_text: My Parallels Machine List
  title: My Parallels Machine List
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017ee44348e6970d-pi
  filename: image_900977.jpg
  alt_text: My Parallels Machine List
  title: My Parallels Machine List
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017c329f6927970b-pi
  filename: image_222599.jpg
  alt_text: My Parallels Machine List
  title: My Parallels Machine List
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017d3ccdf334970c-pi
  filename: image_308961.jpg
  alt_text: My Parallels Machine List
  title: My Parallels Machine List
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017c329f695f970b-pi
  filename: image_288647.jpg
  alt_text: My Parallels Machine List
  title: My Parallels Machine List
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017d3ccdf37f970c-pi
  filename: image_934673.jpg
  alt_text: My Parallels Machine List
  title: My Parallels Machine List
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2017ee44349a4970d-pi
  filename: image_244787.jpg
  alt_text: My Parallels Machine List
  title: My Parallels Machine List
  asset_type: image
