assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201901eca8228970b-pi
  filename: image_225438.jpg
  alt_text: Angled view of a whiteboard
  title: Angled view of a whiteboard
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20192ac8a10bf970d-pi
  filename: image_597324.jpg
  alt_text: Angled view of a whiteboard
  title: Angled view of a whiteboard
  asset_type: image
