assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201a3fccded31970b-pi
  filename: image_970698.jpg
  alt_text: Demoing to a journalist from Greece
  title: Demoing to a journalist from Greece
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201a5117dd011970c-pi
  filename: image_342885.jpg
  alt_text: Demoing to a journalist from Greece
  title: Demoing to a journalist from Greece
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201a5117dd017970c-pi
  filename: image_228478.jpg
  alt_text: Demoing to a journalist from Greece
  title: Demoing to a journalist from Greece
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201a3fccdea06970b-pi
  filename: image_698943.jpg
  alt_text: Demoing to a journalist from Greece
  title: Demoing to a journalist from Greece
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201a5117dcd1e970c-pi
  filename: image_652940.jpg
  alt_text: Demoing to a journalist from Greece
  title: Demoing to a journalist from Greece
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201a3fccdeab9970b-pi
  filename: image_275810.jpg
  alt_text: Demoing to a journalist from Greece
  title: Demoing to a journalist from Greece
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201a5117dce02970c-pi
  filename: image_674764.jpg
  alt_text: Demoing to a journalist from Greece
  title: Demoing to a journalist from Greece
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201a73d890944970d-pi
  filename: image_114984.jpg
  alt_text: Demoing to a journalist from Greece
  title: Demoing to a journalist from Greece
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201a5117dceba970c-pi
  filename: image_807636.jpg
  alt_text: Demoing to a journalist from Greece
  title: Demoing to a journalist from Greece
  asset_type: image
