assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201b8d0c8d281970c-pi
  filename: image_19935.jpg
  alt_text: Demand loading settings
  title: Demand loading settings
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201b8d0c8d28c970c-pi
  filename: image_609528.jpg
  alt_text: Demand loading settings
  title: Demand loading settings
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201bb07e303fa970d-pi
  filename: image_970608.jpg
  alt_text: Demand loading settings
  title: Demand loading settings
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201b7c73f4c1a970b-pi
  filename: image_425602.jpg
  alt_text: Demand loading settings
  title: Demand loading settings
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201bb07e303fe970d-pi
  filename: image_411003.jpg
  alt_text: Demand loading settings
  title: Demand loading settings
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201bb07e37d67970d-pi
  filename: image_699141.jpg
  alt_text: Demand loading settings
  title: Demand loading settings
  asset_type: image
