assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201b8d13fb7b0970c-pi
  filename: image_510417.jpg
  alt_text: Initial design
  title: Initial design
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201bb0859c2ed970d-pi
  filename: image_479484.jpg
  alt_text: Initial design
  title: Initial design
  asset_type: image
