assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201b8d11b7079970c-pi
  filename: image_47551.jpg
  alt_text: Padlocks
  title: Padlocks
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201bb0835dbc3970d-pi
  filename: image_813651.jpg
  alt_text: Padlocks
  title: Padlocks
  asset_type: image
