assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201b7c79526d7970b-pi
  filename: image_728869.jpg
  alt_text: Security warning
  title: Security warning
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201b7c79526db970b-pi
  filename: image_315851.jpg
  alt_text: Security warning
  title: Security warning
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201bb083955cf970d-pi
  filename: image_850355.jpg
  alt_text: Security warning
  title: Security warning
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201bb083955d3970d-pi
  filename: image_508873.jpg
  alt_text: Security warning
  title: Security warning
  asset_type: image
