assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201bb092db2bd970d-pi
  filename: image_137749.jpg
  alt_text: HoloGuide prototype
  title: HoloGuide prototype
  asset_type: image
