assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201bb091ba283970d-pi
  filename: image_401567.jpg
  alt_text: Robot arm in HoloLens app
  title: Robot arm in HoloLens app
  asset_type: image
