assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201bb098f628c970d-pi
  filename: image_66802.jpg
  alt_text: Broken pinch-zoom in Dasher 360
  title: Broken pinch-zoom in Dasher 360
  asset_type: image
