assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e201b7c8ed16c6970b-pi
  filename: image_432900.jpg
  alt_text: Dasher 360 on mobile
  title: Dasher 360 on mobile
  asset_type: image
