assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20240a4f1420f200d-pi
  filename: image_514117.jpg
  alt_text: NEST light gray empty
  title: NEST light gray empty
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20240a4f14219200d-pi
  filename: image_529919.jpg
  alt_text: NEST light gray empty
  title: NEST light gray empty
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2025d9b3bc30d200c-pi
  filename: image_179533.jpg
  alt_text: NEST light gray empty
  title: NEST light gray empty
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2025d9b3bc310200c-pi
  filename: image_964384.jpg
  alt_text: NEST light gray empty
  title: NEST light gray empty
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2025d9b3bc313200c-pi
  filename: image_611382.jpg
  alt_text: NEST light gray empty
  title: NEST light gray empty
  asset_type: image
