assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2025d9b3b4d4f200c-pi
  filename: image_477323.jpg
  alt_text: NEST gray empty
  title: NEST gray empty
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20240a4f0cb59200d-pi
  filename: image_349250.jpg
  alt_text: NEST gray empty
  title: NEST gray empty
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20240a4f0cb5d200d-pi
  filename: image_331979.jpg
  alt_text: NEST gray empty
  title: NEST gray empty
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2025d9b3b4d57200c-pi
  filename: image_87330.jpg
  alt_text: NEST gray empty
  title: NEST gray empty
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e2025d9b3b4d66200c-pi
  filename: image_326781.jpg
  alt_text: NEST gray empty
  title: NEST gray empty
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20240a4f0cb67200d-pi
  filename: image_962792.jpg
  alt_text: NEST gray empty
  title: NEST gray empty
  asset_type: image
