assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20240a517cb1e200b-pi
  filename: image_738614.jpg
  alt_text: Theme setting UI inside Dasher
  title: Theme setting UI inside Dasher
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20240a517cb4b200b-pi
  filename: image_986747.jpg
  alt_text: Theme setting UI inside Dasher
  title: Theme setting UI inside Dasher
  asset_type: image
