assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20282e14b1cdb200b-pi
  filename: image_723496.jpg
  alt_text: Robot occluded by the bridge
  title: Robot occluded by the bridge
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e20282e14b1cfe200b-pi
  filename: image_338560.jpg
  alt_text: Robot occluded by the bridge
  title: Robot occluded by the bridge
  asset_type: image
