assets:
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e202c8d3a3cd9b200d-pi
  filename: image_668335.jpg
  alt_text: Bentway helmet
  title: Bentway helmet
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e202c8d3a36d23200b-pi
  filename: image_290845.jpg
  alt_text: Bentway helmet
  title: Bentway helmet
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e202c8d3a36c3f200b-pi
  filename: image_2226.jpg
  alt_text: Bentway helmet
  title: Bentway helmet
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e202c8d3a3cdb0200d-pi
  filename: image_473992.jpg
  alt_text: Bentway helmet
  title: Bentway helmet
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e202c8d3a3ccc9200d-pi
  filename: image_591184.jpg
  alt_text: Bentway helmet
  title: Bentway helmet
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e202c8d3a36d39200b-pi
  filename: image_571213.jpg
  alt_text: Bentway helmet
  title: Bentway helmet
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e202c8d3a3ccce200d-pi
  filename: image_434877.jpg
  alt_text: Bentway helmet
  title: Bentway helmet
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e202c8d3a36c46200b-pi
  filename: image_989581.jpg
  alt_text: Bentway helmet
  title: Bentway helmet
  asset_type: image
- url: https://through-the-interface.typepad.com/.a/6a00d83452464869e202c8d3a36d32200b-pi
  filename: image_750669.jpg
  alt_text: Bentway helmet
  title: Bentway helmet
  asset_type: image
