assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0167666786e4970b-pi
  filename: image_277951.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b016766678972970b-pi
  filename: image_673235.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01630573a239970d-pi
  filename: image_443484.jpg
  alt_text: image
  title: image
  asset_type: image
