assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017d424c71c5970c-pi
  filename: image_201792.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017c381d4e06970b-pi
  filename: image_314062.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017d424c727f970c-pi
  filename: image_96661.jpg
  alt_text: image
  title: image
  asset_type: image
