assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017c3554577e970b-pi
  filename: image_288949.jpg
  alt_text: clip_image001
  title: clip_image001
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017ee6f7b101970d-pi
  filename: image_184104.jpg
  alt_text: clip_image001
  title: clip_image001
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017d3f834346970c-pi
  filename: image_900786.jpg
  alt_text: clip_image001
  title: clip_image001
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017d3f83437a970c-pi
  filename: image_90209.jpg
  alt_text: clip_image001
  title: clip_image001
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017d3f834391970c-pi
  filename: image_172307.jpg
  alt_text: clip_image001
  title: clip_image001
  asset_type: image
