assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01901ea10280970b-pi
  filename: image_754489.jpg
  alt_text: Autodesk Exchange Store in Portuguese
  title: Autodesk Exchange Store in Portuguese
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0192ac606bf2970d-pi
  filename: image_380342.jpg
  alt_text: Autodesk Exchange Store in Portuguese
  title: Autodesk Exchange Store in Portuguese
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01901ea102c7970b-pi
  filename: image_652080.jpg
  alt_text: Autodesk Exchange Store in Portuguese
  title: Autodesk Exchange Store in Portuguese
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0192ac606c47970d-pi
  filename: image_313556.jpg
  alt_text: Autodesk Exchange Store in Portuguese
  title: Autodesk Exchange Store in Portuguese
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01901ea102e8970b-pi
  filename: image_821822.jpg
  alt_text: Autodesk Exchange Store in Portuguese
  title: Autodesk Exchange Store in Portuguese
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0192ac606c6f970d-pi
  filename: image_787182.jpg
  alt_text: Autodesk Exchange Store in Portuguese
  title: Autodesk Exchange Store in Portuguese
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01910496f3ea970c-pi
  filename: image_25038.jpg
  alt_text: Autodesk Exchange Store in Portuguese
  title: Autodesk Exchange Store in Portuguese
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0192ac606cd4970d-pi
  filename: image_312266.jpg
  alt_text: Autodesk Exchange Store in Portuguese
  title: Autodesk Exchange Store in Portuguese
  asset_type: image
