assets:
- url: http://adndevblog.typepad.com/files/test_dynamic_load.zip
  filename: test_dynamic_load.zip
  alt_text: Download Test_dynamic_load
  title: Download Test_dynamic_load
  asset_type: file
