assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01a73e100f86970d-pi
  filename: image_930738.jpg
  alt_text: Balance Rocks French Riviera
  title: Balance Rocks French Riviera
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01a73e0ed65a970d-pi
  filename: image_336505.jpg
  alt_text: Balance Rocks French Riviera
  title: Balance Rocks French Riviera
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c6d8ef08970b-pi
  filename: image_717965.jpg
  alt_text: Balance Rocks French Riviera
  title: Balance Rocks French Riviera
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d062d794970c-pi
  filename: image_715842.jpg
  alt_text: Balance Rocks French Riviera
  title: Balance Rocks French Riviera
  asset_type: image
