assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c7cfb62e970b-pi
  filename: image_25037.jpg
  alt_text: bday quote
  title: bday quote
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1599c7d970c-pi
  filename: image_255057.jpg
  alt_text: bday quote
  title: bday quote
  asset_type: image
