assets:
- url: https://around-the-corner.typepad.com/.a/6a0163057a21c8970d01b7c8586cce970b-pi
  filename: image_6d2ad5.jpg
  alt_text: CLIC Version Mismatch
  title: CLIC Version Mismatch
  asset_type: image
- url: https://around-the-corner.typepad.com/.a/6a0163057a21c8970d01b7c8586cd7970b-pi
  filename: image_c52ff8.jpg
  alt_text: Uninstall is missing
  title: Uninstall is missing
  asset_type: image
- url: https://around-the-corner.typepad.com/.a/6a0163057a21c8970d01bb08fbfba2970d-pi
  filename: image_a86443.jpg
  alt_text: Uninstall in the right click menu
  title: Uninstall in the right click menu
  asset_type: image
- url: https://around-the-corner.typepad.com/.a/6a0163057a21c8970d01bb08fbfbaa970d-pi
  filename: image_56a047.jpg
  alt_text: Maya tries to find files in incorrect path
  title: Maya tries to find files in incorrect path
  asset_type: image
