assets:
- url: https://around-the-corner.typepad.com/.a/6a0163057a21c8970d01b7c91d3986970b-800wi
  filename: image_a28637.jpg
  alt_text: Vscode1
  title: Vscode1
  asset_type: image
- url: https://around-the-corner.typepad.com/.a/6a0163057a21c8970d01bb09c07068970d-800wi
  filename: image_5ee01b.jpg
  alt_text: Vscode2
  title: Vscode2
  asset_type: image
- url: https://around-the-corner.typepad.com/.a/6a0163057a21c8970d01bb09c0707a970d-800wi
  filename: image_d8ff0f.jpg
  alt_text: Vscode3
  title: Vscode3
  asset_type: image
