comments:
- author: Jason Howden
  email: jason@archaus.co.nz
  ip: 121.73.56.145
  url: http://www.revittv.com
  date: '2009-01-01 22:48:32'
  body: Have you seen the Revit Drawing Manager at RevitTV.com?...
- author: Jeremy Tammik
  email: ''
  ip: 132.188.32.100
  url: http://profile.typepad.com/1218580759s22477
  date: '2009-01-02 05:42:34'
  body: Hi Jason. No, I had not. Thank you for the pointer. Happy new year to you!
    Cheers, Jeremy.
- author: 'Michelle '
  email: michellelouw@pdt.com.au
  ip: 61.29.67.174
  url: http://www.bimboombam.wordpress.com
  date: '2009-01-04 17:30:21'
  body: "Hi Jeremy\nCan you please contact me direclty on my email so that I can ask\
    \ you questions off line. \nMany Thanks"
- author: Jeremy Tammik
  email: ''
  ip: 89.59.97.185
  url: http://profile.typepad.com/1218580759s22477
  date: '2009-01-05 02:09:11'
  body: Hi Michelle, sure, I sent you a direct email. However, please be aware that
    I have very limited time for exploring new questions, and most of the information
    I publish here comes from existing knowledge. Cheers, Jeremy.
- author: Jurgita
  email: jurgita.spejeraite@aga-cad.lt
  ip: 77.241.201.221
  url: http://www.tools4revit.com
  date: '2009-02-09 07:25:12'
  body: "Hello, \n\nwe have some tools for Revit. It helps Revit users to avoid problems\
    \ and increase work efficiency.\n\nBR\nJurgita\n-----"
