comments:
- author: Rod Howarth
  email: itfetish@gmail.com
  ip: 124.171.135.209
  url: http://roddotnet.blogspot.com
  date: '2008-10-14 22:16:38'
  body: "Also useful for anyone who is a VB coder and wants to convert samples is\
    \ the many VB to C# code converters available:\nhttp://www.google.com.au/search?source=ig&hl=en&rlz=1G1GGLQ_ENAU244&=&q=C%23+to+VB+code+converter&btnG=Google+Search&meta=\
    \ \n\nsuch as:\nhttp://www.developerfusion.com/tools/convert/csharp-to-vb/ \n\
    and\nhttp://www.carlosag.net/Tools/CodeTranslator/\n\nthey may not do whole projects\
    \ but they can help you decipher the samples!"
- author: Jeremy
  email: jeremy.tammik@eur.autodesk.com
  ip: 80.58.205.45
  url: http://thebuildingcoder.typepad.com
  date: '2008-10-27 05:38:03'
  body: "Hi Rod,\n\nThank you very much for your comment. It prompted me to write\
    \ a post mentioning Lutz Roeder's wonderful Reflector analyser and IL decompilation\
    \ tool, available at \n\nhttp://www.aisto.com/roeder/dotnet\n\nI am in the process\
    \ of posting it right now ... \n\nThank you for the inspiration!\n\nBest regards,\n\
    \nJeremy\n\n-----"
