comments:
- author: Kesari Mudhagouni
  email: kmudhagouni@dcstrategies.net
  ip: 75.148.5.23
  url: ''
  date: '2013-12-16 15:23:01'
  body: 'Hi Jeremy,


    Is it possible to customize DWG export settings which can change layer visibilities
    in default CAD export. For example, is it possible to keep room boundary lines
    layer to be turned "on" as default instead of turned "off" as in the current CAD
    layer export settings? Please let me know.


    Thank you,


    Kesari'
- author: Jeremy Tammik
  email: ''
  ip: 87.148.200.168
  url: http://profile.typepad.com/jeremytammik
  date: '2013-12-20 09:55:34'
  body: 'Dear Kesari,


    You can seldom programmatically make any changes that are not also supported by
    the user interface.


    Are the settings you want available in the UI?


    Cheers, Jeremy.'
- author: Kesari Mudhagouni
  email: kmudhagouni@dcstrategies.net
  ip: 75.148.5.23
  url: ''
  date: '2014-01-13 16:59:55'
  body: 'No they are not available in the UI

    -----'
