comments:
- author: Miss Mary
  email: avizaz@gmail.com
  ip: 212.143.150.160
  url: http://ippm.edu.my/portfolio/pg/pages/view/388080
  date: '2011-10-25 15:20:31'
  body: 'It also applies to other products, with a slight changes.

    -----'
