comments:
- author: Alnjxn
  email: ''
  ip: 68.175.92.113
  url: http://profile.typepad.com/alnjxn
  date: '2012-06-23 19:00:00'
  body: 'The Snoop tool is showing me the following enumeration values in Revit MEP
    2012


    1 Architectural

    2 Structural

    4 Mechanical

    8 Electrical

    4095 Coordination'
- author: Jeremy Tammik
  email: ''
  ip: 87.146.160.15
  url: http://profile.typepad.com/jeremytammik
  date: '2012-06-24 17:12:09'
  body: 'Dear Alnjxn,


    Right you are, I see the same and corrected the post.


    In any case, in Revit 2013, due to the one-box solution, all three flavours may
    exist in parallel, so consecutive numbers could not be used at all, and individual
    bits that can be switched on and off individually is the only way to go.


    Thank you for pointing this out!


    Cheers, Jeremy.

    -----'
