comments:
- author: sangsen
  email: sangsen123@gmail.com
  ip: 59.163.205.194
  url: ''
  date: '2012-02-06 05:36:48'
  body: "Hi..Jeremy,\n\n   Please help me to achieve Revit like Cancel button(Behaviour)."
- author: Jeremy Tammik
  email: ''
  ip: 82.220.1.196
  url: http://profile.typepad.com/jeremytammik
  date: '2012-02-08 05:44:05'
  body: 'Dear Sangsen,


    I don''t know exactly what you mean by "Revit like Cancel button(Behaviour)".


    The Revit API does not provide full access to all user interface features.


    What is possible is demonstrated by the Revit SDK samples and the ADN Revit API
    introductory training material, especially the Ribbon samples.


    In many cases, if you want any kind of complex interaction, you will have to build
    it yourself using the standard .NET framework and Windows Forms, for instance.


    Cheers, Jeremy.'
- author: Bryan Thatcher
  email: ''
  ip: 68.143.90.26
  url: http://profile.typepad.com/bryanthatcher
  date: '2012-06-05 14:03:16'
  body: Can you please give an example of registering the DialogBoxShowing event handler
    at the beginning of an external command? I'm having a similar problem. Thank you!
- author: Jeremy Tammik
  email: ''
  ip: 216.52.185.72
  url: http://profile.typepad.com/jeremytammik
  date: '2012-06-05 14:30:02'
  body: 'Dear Bryan,


    There is hardly anything to show, since the code is just about identical.


    Therefore I do not understand your reason for asking this.


    The external command ExternalCommandData input argument provides access to the
    UIApplication instance, and you subscribe to DialogBoxShowing on that just like
    on the UIControlledApplication above.


    Cheers, Jeremy.'
- author: Rey
  email: anagnam@yahoo.com
  ip: 37.210.168.26
  url: ''
  date: '2014-08-28 09:50:24'
  body: "Hello Jeremy,\n\nIs it possible to call an external API (GET) on the OnStartup\
    \ function and (POST) on the OnShutdown of IExternalDBApplication? \n\nThanks"
- author: Jeremy Tammik
  email: ''
  ip: 132.188.32.206
  url: http://profile.typepad.com/jeremytammik
  date: '2014-08-28 10:34:21'
  body: 'Dear Rey,


    Yes, I see no reason whatsoever why that should interfere with Revit in any way.


    My guess is that Revit will neither notice nor care.


    Cheers, Jeremy.'
- author: Rey
  email: anagnam@yahoo.com
  ip: 37.210.168.26
  url: ''
  date: '2014-09-02 05:25:16'
  body: 'Thank you very much Jeremy for your confirmation. - cheers!

    -----'
