comments:
- author: Guy Robinson
  email: info@redbolts.com
  ip: 60.234.255.173
  url: ''
  date: '2011-01-05 15:43:29'
  body: "Hi Jeremy, \nUIAutomation is very useful esp for functional testing of Revit.\
    \ However it's not the nicest of API's. FYI, White <a href=\"http://white.codeplex.com/\"\
    >http://white.codeplex.com/</a> is a nice wrapper around UIAutomation which simplifies\
    \ usage considerably. \n\nHappy New Year!! Guy"
- author: Jeremy Tammik
  email: ''
  ip: 188.104.23.15
  url: http://profile.typepad.com/jeremytammik
  date: '2011-01-08 05:31:45'
  body: 'Hi Guy,


    Happy New Year to you too, and thank you for the link!


    I passed it on to Rudolf, and he says: White seems to be worth a look. Interesting
    info on page, e.g.:


    "Please do not trust UISpy, it doesn''t tell everything even for standard controls."


    "The default performance of white tests might be slow if there are a lot of automation
    elements on the screen."


    And by the way, Rudolf has LOTS more ideas up his sleeve...


    Cheers, Jeremy.'
- author: Guy Robinson
  email: info@redbolts.com
  ip: 60.234.255.173
  url: ''
  date: '2011-01-12 02:23:22'
  body: "Hi Jeremy,\n\nNo don't use UISpy. Use Inspect Objects which comes with SDk\
    \ 7.1 and is x64. That combined with Spy++ does all the digging under the covers\
    \ you need (in general). \n\nUIAutomation as part of .NET and as a MSFT technology\
    \ I figure is as close as we can get to official support for unsupported API's\
    \ ;-)\n\nCheers, Guy"
- author: Mustafa Salah
  email: ''
  ip: 197.35.80.238
  url: http://profile.typepad.com/6p017c3683896b970b
  date: '2013-07-13 02:51:31'
  body: 'Hello

    I have tried the Coded UI test of visual studio 2010 on Revit MEP 2012 to test
    the export to DWG file from the Revit menu but for some reason vs fails to capture
    the mouse click on the Export menu item ... any ideas??'
- author: Jeremy Tammik
  email: ''
  ip: 87.148.222.137
  url: http://profile.typepad.com/jeremytammik
  date: '2013-09-05 08:06:14'
  body: 'Dear Mustafa,


    Nope, sorry, you are definitely on your own here...


    Cheers, Jeremy.'
- author: MarcosMateoq
  email: ''
  ip: 190.114.248.120
  url: http://profile.typepad.com/marcosmateoq
  date: '2014-05-22 12:34:49'
  body: 'Hi Jeremy

    I am developing a Revit ADD-IN from Visual Basic 2012 and need to open the dialog
    ''New Project''. Could you give me an example of the code I should use?.'
- author: Jeremy Tammik
  email: ''
  ip: 87.148.203.246
  url: http://profile.typepad.com/jeremytammik
  date: '2014-05-28 11:25:08'
  body: 'Dear Marcos,


    Phillip, Revitalizer and I answered your question on the Revit API discussion
    forum, twice over:


    <a href="http://forums.autodesk.com/t5/Revit-API/how-to-open-the-dialog-New-Project-from-my-application-Visual/td-p/5045102">http://forums.autodesk.com/t5/Revit-API/how-to-open-the-dialog-New-Project-from-my-application-Visual/td-p/5045102</a>


    <a href="http://forums.autodesk.com/t5/Revit-API/Need-example-of-open-New-Proyect-dialog-box-Revit-from-visual/td-p/5050118">http://forums.autodesk.com/t5/Revit-API/Need-example-of-open-New-Proyect-dialog-box-Revit-from-visual/td-p/5050118</a>


    That ought to be enough  :-)


    Cheers, Jeremy.

    -----'
