comments:
- author: Junyu
  email: owen1226@gmail.com
  ip: 216.165.204.229
  url: ''
  date: '2011-03-21 13:36:11'
  body: 'Hi, Sir


    It is a nice Website, thanks. I get a question to you. I try to create model lines
    using the method in your blog, but the model lines will display after shuting
    down my application. I want to know how I can keep the model lines permanently?'
- author: Jeremy Tammik
  email: ''
  ip: 213.210.236.146
  url: http://profile.typepad.com/jeremytammik
  date: '2011-03-21 13:55:58'
  body: 'Dear Junyu,


    Thank you for your appreciation!


    If you see those model lines displayed after you have shut down the application,
    it is probably due to some dirt on your screen  :-)


    If you add model lines to the Revit document, then they are stored in the database
    and will remain there when the document is saved. Have you tried saving the document?  :-)


    Cheers, Jeremy.'
- author: Junyu
  email: owen1226@gmail.com
  ip: 132.205.164.95
  url: ''
  date: '2011-03-21 15:23:48'
  body: Thanks for your response. I tried to save, but the new saved file just shows
    after the model line displaying.
- author: Dale Bartlett
  email: dale.bartlett@realtimeinternational.com.au
  ip: 212.72.17.154
  url: http://www.realtimeinternational.com.au
  date: '2011-03-22 01:36:33'
  body: Hi Jeremy, You picked a good time to be visiting Arabia... I'm based in Oman,
    so if you want a stopover on your way home, my wife and I would be delighted to
    give you our royal tour. It's a beautiful, interesting country, with beaches.
    Unfortunately I overlooked the Saudi training otherwise I would have joined. Regards,
    Dale
- author: Jeremy Tammik
  email: ''
  ip: 82.220.1.199
  url: http://profile.typepad.com/jeremytammik
  date: '2011-03-29 18:00:47'
  body: 'Hi Dale,


    Wow, thank you very much for your kind invitation! Originally Saikat was scheduled
    to give this training, so my visit in Saudi Arabia was planned at short notice
    and I had to rush home immediately, unfortunately. I am already back in Switzerlnd
    again. No rest for the wicked. I heard from friends that Oman is indeed very beautiful.
    I had no idea that you are based there.


    Sorry to hear that you missed the training, when you would have been interested.
    We would have loved having you!


    Cheers, Jeremy.'
- author: Dan Rumery
  email: Dan_Rumery@bvn.com.au
  ip: 210.18.194.130
  url: http://blog.bvn-usyd.com/
  date: '2011-04-01 00:53:25'
  body: 'Hi Jeremy,


    The intersection results I''m getting from the Revit API appear to contradict
    the documentation (Revit 2011 SDK) on computing intersections of lines in Revit.


    Lines that are disjoint are reported as such, correctly. However, lines that intersect
    at the endpoints *alone* report "Subset" as opposed to the documented "Overlap",
    and lines whose intersection is a line report as "Equal" even if the line of interection
    is a strict subset of both, again as opposed to the documented "Overlap" result.
    I don''t know whether curves such as arcs and splines will return the same kinds
    of results I''ve been getting for straight lines.


    Furthermore, when "Equal" is returned for *strict subset* intersections as above,
    I don''t get any IntersectionResultArray back (Revit sets it to null).


    Because of this behaviour I''m unable to get the endpoints of any strict subset
    intersection between lines. Any ideas?'
- author: Jeremy Tammik
  email: ''
  ip: 82.220.1.196
  url: http://profile.typepad.com/jeremytammik
  date: '2011-04-01 05:32:09'
  body: "Dear Dan,\n\nThat sounds very worrying! \n\nIf you are an ADN member, please\
    \ submit a DevHelp Online case with some sample code demonstrating the behaviour.\
    \ Otherwise, please send me an email with a minimal project attached, so we can\
    \ take a look.\n\nThank you!\n\nCheers, Jeremy."
- author: Dan
  email: dan_rumery@bvn.com.au
  ip: 210.18.194.130
  url: http://blog.bvn-usyd.com/
  date: '2011-04-06 22:59:05'
  body: 'Will do, thanks Jeremy!


    p.s. when I wrote "strict subset of both lines" I actually meant a subset of both
    lines, non-equal to either line. (An intersection being a strict subset of *both*
    (straight) lines would not be possible, heh.)


    We''re recently joined the ADN so I''ll try to put something together for a DevHelp
    submission.'
- author: Dan
  email: dan_rumery@bvn.com.au
  ip: 210.18.194.130
  url: http://blog.bvn-usyd.com/
  date: '2011-04-06 23:07:18'
  body: p.p.s. Ignore that p.s. above, "strict subset of both lines" is indeed what
    I meant. I've momentarily confused myself on the definition of strict subset.
- author: Jeremy Tammik
  email: ''
  ip: 82.220.1.196
  url: http://profile.typepad.com/jeremytammik
  date: '2011-04-08 01:47:36'
  body: "Dear Dan,\n\nCongratulations on becoming an ADN member! \n\nI am eagerly\
    \ awaiting your DevHelp Online query and sample code. \n\nMeanwhile, I appended\
    \ your notes above to the case I raised with the development team. \n\nThank you!\n\
    \nCheers, Jeremy.\n-----"
