comments:
- author: Sample CV
  email: ''
  ip: 122.169.222.242
  url: http://profile.typepad.com/samplecv
  date: '2011-03-16 23:59:59'
  body: 'This is very cool blog with useful information about handling DPI scaling
    in .NET application forms.Sample Forms

    -----'
