comments:
- author: Rudolf Honke
  email: rudolf.honke@acadGraph.de
  ip: 193.158.119.50
  url: http://www.acadGraph.de
  date: '2012-10-12 05:31:32'
  body: 'Hi Jeremy,


    one could say that AutoCAD is related to Revit in the same manner as a simple
    text editor is related to MS Word.


    If you type in some text in the text editor, your letters will be displayed in
    the same format you type them.


    But if you type in some text in a Word document, there is an AI working in the
    background that makes real-time orthographical checks or it decides that you want
    to write a letter (with dialogs popping up...).


    So, from my own experience, coding for Revit may result in fighting against the
    AI.


    Cheers,

    Rudolf'
- author: Jeremy Tammik
  email: ''
  ip: 46.14.153.235
  url: http://profile.typepad.com/jeremytammik
  date: '2012-10-12 09:33:37'
  body: 'Dear Rudolf,


    We-e-elll, ye-e-es...


    In any case, we certainly agree that the most important thing is to know what
    Revit does and how it should be used properly before even starting to think about
    how to improve anything, yes?


    And that is a big subject with a few surprising caveats, especially coming from
    some other system and assuming you already know it all...


    Cheers, Jeremy.'
- author: Ahmed
  email: ahmad4343@live.com
  ip: 2.88.59.113
  url: ''
  date: '2012-11-03 03:45:21'
  body: 'i want script that can change the background of revit from black to any color
    say grey ? is that possible with revit API ?

    i hate pure white background and pure black background'
- author: Jeremy Tammik
  email: ''
  ip: 87.146.184.36
  url: http://profile.typepad.com/jeremytammik
  date: '2012-11-14 03:46:29'
  body: 'Dear Ahmed,


    This may or may not be possible in the UI. Certainly not in the API.


    Cheers, Jeremy.

    -----'
