comments:
- author: Ariel
  email: 846081597@qq.com
  ip: 61.132.35.43
  url: ''
  date: '2014-03-19 04:57:46'
  body: 'Dear Jeremy,

    I have a  headache problem.

    How can I fast read the dimensions parameters of lofting model,as well as area
    and volume attributes.

    And if I change the Long or Width parameter,whether the model can follow the change??

    Sorry for my poor English.

    Thanks,

    Ariel'
- author: Ariel
  email: 846081597@qq.com
  ip: 61.132.35.43
  url: ''
  date: '2014-03-19 05:09:50'
  body: 'Dear Jeremy,

    I am a beginner of revit secondary development,please exhibitions.

    Thanks,Ariel'
- author: Jeremy Tammik
  email: ''
  ip: 87.146.183.204
  url: http://profile.typepad.com/jeremytammik
  date: '2014-03-19 08:47:53'
  body: 'Dear Ariel,


    Please go through the standard getting started material. It addresses all these
    questions:


    <a href="http://thebuildingcoder.typepad.com/blog/about-the-author.html#2">http://thebuildingcoder.typepad.com/blog/about-the-author.html#2</a>


    Good luck beginning and continuing, and I hope you can quickly let go of all your
    headaches!


    Cheers, Jeremy.'
- author: Ariel
  email: 846081597@qq.com
  ip: 61.132.35.43
  url: ''
  date: '2014-03-23 23:36:41'
  body: 'Dear Jeremy,

    Thank for your reply,I have just read some sample codes in your blog.Now i have
    a problem that how can i know the new form of namespace in 2014 instead of 2010,when
    i compile the codes in 2010,it always has problems and i cannot find the corresponding
    new form of namespace in 2014.

    Thanks a lot for your help.'
- author: Jeremy Tammik
  email: ''
  ip: 87.102.230.236
  url: http://profile.typepad.com/jeremytammik
  date: '2014-03-24 01:41:30'
  body: 'Dear Ariel,


    Only one single release of the Revit API included significant namespace reorganisation,
    for the transition from Revit 2010 to 2011:


    <a href="http://thebuildingcoder.typepad.com/blog/2013/02/whats-new-in-the-revit-2011-api.html">http://thebuildingcoder.typepad.com/blog/2013/02/whats-new-in-the-revit-2011-api.html</a>


    Search in there for "Changes to the Revit API namespaces".


    Cheers, Jeremy.'
- author: HuanTing
  email: huanting.chen@gmail.com
  ip: 140.112.218.177
  url: ''
  date: '2014-03-24 04:14:25'
  body: 'Hi, Jeremy,

    Is it possible for a central file to store project-based information within a
    RVT file? Because the ProjectInfo element is not accessible under the circumstance.'
- author: Jeremy Tammik
  email: ''
  ip: 87.102.230.236
  url: http://profile.typepad.com/jeremytammik
  date: '2014-03-24 04:30:22'
  body: 'Dear HuanTing,


    Yes, that is definitely possible.


    I would still have expected the ProjectInfo element to be accessible.


    I learned that many companies restrict access to it in workshared environments,
    to avoid enabling people to update elements that affect absolutely everybody in
    the team.


    The best way to store add-in data or project information is to isolate it, e.g.
    by creating your own DataStorage element and using that:


    <a href="http://thebuildingcoder.typepad.com/blog/2012/05/devblog-devcamp-element-and-project-wide-data.html#5">http://thebuildingcoder.typepad.com/blog/2012/05/devblog-devcamp-element-and-project-wide-data.html#5</a>


    Cheers, Jeremy.

    -----'
