comments:
- author: Ed
  email: edh777@gmail.com
  ip: 5.199.130.188
  url: ''
  date: '2014-02-05 22:51:09'
  body: 'Hi Jeremy


    Do you know of any way we could use to find the visibility settings of FilledRegion''s?
    This one does not seem to have that parameter.


    The same goes for a number of other things like Walls.


    Thanks,


    Ed'
- author: Jeremy Tammik
  email: ''
  ip: 132.188.32.25
  url: http://profile.typepad.com/jeremytammik
  date: '2014-02-06 03:05:33'
  body: "Dear Ed, \n\nNope, sorry.\n\nI'll ask about that, though.\n\nCheers, Jeremy."
- author: Ed
  email: edh777@gmail.com
  ip: 37.221.162.226
  url: ''
  date: '2014-02-06 03:58:34'
  body: 'Thanks for letting me know Jeremy. I was going almost crazy looking for a
    way for this one.

    -----'
