comments:
- author: Preston Smith
  email: psmith@brplusa.com
  ip: 64.121.204.144
  url: ''
  date: '2015-02-07 17:04:41'
  body: 'Hi Jeffrey - firstly thanks so much for your continued work; I started out
    coding learning from your blogs and podcasts and its a constant reference for
    me! I know you''ve covered this item in the past but it seems to be a recurring
    problem in my code, not sure if you can give a hand. (I''m trying ADN and StackOverflow
    at the same time but no one seems to have a similar problem yet). Long story short,
    I''m imitating the copy-monitor process by attempting to programmatically place
    objects in a model - unfortunately I''m running to errors when attempting to host
    to an item in the linked model itself. I''ve used multiple overloads of the NewFamilyInstance
    as well as ones that include the CreateLinkReference but still no luck. Each error
    comes with either the non-useful and dreaded "External Exception Error" or "Family
    cannot be placed as hosted on an input face reference, because its FamilyPlacementType
    is not WorkPlaneBased" (which it is of course). I''ve even tried the Prompt placement
    method, which works but doesn''t tell me why the programmatic version doesn''t.
    Any ideas? Here''s a link to the Stack question for more info:


    <a href="http://stackoverflow.com/q/28387888/1732184">http://stackoverflow.com/q/28387888/1732184</a>'
- author: Jeremy Tammik
  email: ''
  ip: 2.235.111.246
  url: http://profile.typepad.com/jeremytammik
  date: '2015-02-10 03:21:16'
  body: 'Dear Preston,


    Thank you for your appreciation.


    Sorry I have no immediate answer to your question.


    I see your thread on it in the Revit API discussion forum as well:


    <a href="http://forums.autodesk.com/t5/revit-api/place-a-family-instance-on-a-linked-host/td-p/5499313">http://forums.autodesk.com/t5/revit-api/place-a-family-instance-on-a-linked-host/td-p/5499313</a>


    That makes sense, and I hope that the community at large will be able to help.


    Cheers,


    Jeremy

    -----'
