comments:
- author: Ludovic Gnemmi
  email: ''
  ip: 78.119.208.39
  url: http://profile.typepad.com/ludovicgnemmi
  date: '2012-08-09 13:30:35'
  body: 'I''m working with MG2011 and i don''t see any DBMaxLockers and DBMaxTransactions
    variable in my serverconfig file.

    How can we solve this issue. I''m encountering this log message since i have a
    big number of layers in my map (300). Thanks for your help'
- author: Partha
  email: partha.sarkar@autodesk.com
  ip: 115.112.233.72
  url: ''
  date: '2012-08-23 02:35:39'
  body: 'Hi Ludovic,


    DBMaxLockers and DBMaxTransactions are new in AIMS 2013. You could try using AIMS
    2013 and set the appropriate values for these and see if it helps in your dataset
    / project.


    Thanks,

    Partha'
- author: Mobin
  email: mobin.rehman@gmail.com
  ip: 182.178.39.239
  url: ''
  date: '2012-11-19 08:43:35'
  body: "Hi Partha \nI have tried, but error is same, can you please specifically\
    \ tell me which parameter i need to configure, my problem is that i have 20000\
    \ points coming from db.  when i try to select the all points at once, it gives\
    \ me  DB_LOG_MEMORY_BUFFER FULL.\n\nPLEASE ADVICE WHICH parameter i need to reconfigure\n\
    thanks"
- author: Partha Sarkar
  email: ''
  ip: 59.92.137.109
  url: http://profile.typepad.com/6p0168e7e4ef23970c
  date: '2012-11-26 04:52:56'
  body: 'Hi Mobin,



    Please see the list of the variable and what they are related to from the above
    blog post. You might have to play around with them to see what gives you best
    result. It''s difficult for me to pin-point the variable / value which will fix
    the issue in your set-up, sorry.


    Thanks,

    Partha

    ADN

    -----'
