comments:
- author: Geurt
  email: geurt@kariwa.co.za
  ip: 41.146.62.41
  url: ''
  date: '2012-11-16 02:41:05'
  body: 'Partha

    Is this also usable to access "Flow Rate"? I need to access "Flow Rate" to use
    in a Excel spreadsheet.


    Geurt'
- author: Partha Sarkar
  email: ''
  ip: 59.92.137.109
  url: http://profile.typepad.com/6p0168e7e4ef23970c
  date: '2012-11-26 04:48:57'
  body: 'Hi Geurt,


    "Flow Rate" is not exposed. I am logging a wish list to expose it and other two
    - "Junction Loss", "Return Period" in future release of Civil 3D.


    Thanks,

    Partha'
- author: Neyton
  email: neyton@yahoo.com
  ip: 187.60.121.62
  url: http://tbn2.blogspot.com
  date: '2012-11-28 12:00:27'
  body: 'Dim o As Part ''...

    Dim pf as PartFamily ''...

    dim ps as PartSize ''...


    o.AcadObject.SwapPartFamilyAndSize(pf.GUID, ps.AcadObject)


    directly, problem?


    -----'
