comments:
- author: Dave B
  email: dcbosworth@btinternet.com
  ip: 212.183.128.58
  url: ''
  date: '2013-12-11 02:44:19'
  body: When I try this example (using 2013, and VB .Net), I am unable to load the
    AeccXSurvey and AeccXUiSurvey type libraries. Am I added the correct references?
- author: Partha Sarkar
  email: ''
  ip: 203.202.234.243
  url: http://profile.typepad.com/6p0168e7e4ef23970c
  date: '2013-12-11 02:49:16'
  body: "Hi Dave -\n\nFor Civil 3D 2013 COM libs, please refer to the following topic\
    \ - \n\nhttp://adndevblog.typepad.com/infrastructure/2012/04/com-references-on-civil-3d-2013.html\n\
    \nThanks,\nPartha"
- author: Dave B
  email: dcbosworth@btinternet.com
  ip: 212.183.128.58
  url: ''
  date: '2013-12-11 09:32:52'
  body: 'Thanks, that was very useful!

    -----'
