comments:
- author: Steve Hill
  email: steve@redtransitconsultants.com
  ip: 108.162.216.232
  url: http://www.redtransitconsultants.com
  date: '2014-04-25 07:45:19'
  body: 'Thanks Augusto.


    Very helpful post. One thing I noticed with 2014 code in 2015 is that even though
    the code runs, dialog boxes seem to shrink a bit and don''t appear as they do
    in 2014. I''ll ultimately be upgrading my apps to VS 2012 specifically for 2015
    anyway, but I am curious. Any ideas as to why?'
- author: Augusto Goncalves
  email: ''
  ip: 108.162.219.76
  url: http://profile.typepad.com/6p0168e7e7c9dd970c
  date: '2014-04-25 07:52:21'
  body: 'Steve,


    I''m not aware of any issue. Also, tried on my end (same DLL on both version)
    and the Forms are exactly the same (size, style, etc).


    If you have a repro sample, please send to me, will investigate.


    Regards,

    Augusto Goncalves'
- author: saman
  email: saman_b185@yahoo.com
  ip: 31.184.151.235
  url: ''
  date: '2014-11-17 23:40:38'
  body: 'Hi

    I''m going with the programming language C # in Visual Studio AutoCAD software
    developed.plz help me.'
- author: Augusto Goncalves
  email: ''
  ip: 132.188.64.149
  url: http://profile.typepad.com/6p0168e7e7c9dd970c
  date: '2014-11-18 07:15:12'
  body: 'Saman,


    These VS settings are independent of language, you need to configure for both
    VB.NET and C#. If you have a specific question, please use our forum: http://forums.autodesk.com/t5/autocad-civil-3d-customization/bd-p/190


    Regards,

    Augusto Goncalves'
- author: Borja1980
  email: Borja_delcampo@hotmail.com
  ip: 90.165.187.86
  url: ''
  date: '2015-08-23 14:42:38'
  body: 'Hi. I have done the steps described here, and the proyect compiles perfectly.
    However, when i start debuging, acad.exe starts executing, and allways crashes.
    I hace reinstalled visual studio 2012 and civil2015, but the problem persist.
    I would like to know i somebody has run into a similar problem, and has been able
    to finde a solution.

    Thanks'
- author: Augusto Goncalves
  email: ''
  ip: 177.43.194.106
  url: http://profile.typepad.com/6p0168e7e7c9dd970c
  date: '2015-08-24 04:42:16'
  body: "Hi,\n\nI would need more details on what's happening (error message). \n\n\
    You can also try with the template at http://adndevblog.typepad.com/infrastructure/2014/09/civil-3d-project-template-for-visual-studio.html\n\
    \nRegards,\nAugusto Goncalves"
- author: hade
  email: wrya.hade@yahoo.com
  ip: 93.91.194.245
  url: http://www.institueerbil.com
  date: '2015-09-23 08:58:55'
  body: "hellow \n i want create programing for optimazation vertical and horizontal\
    \ alignment, do you have any sugestion for me."
- author: Augusto Goncalves
  email: ''
  ip: 177.43.194.106
  url: http://profile.typepad.com/6p0168e7e7c9dd970c
  date: '2015-09-23 09:13:15'
  body: 'Hi, this could give you a starting point: http://adndevblog.typepad.com/infrastructure/2012/08/replacing-alignment-entities.html


    Regards,

    Augusto Goncalves

    -----'
