comments:
- author: Per Jonsson
  email: per.jonsson@65nord.se
  ip: 95.195.21.37
  url: ''
  date: '2011-06-13 15:59:28'
  body: 'Hi!

    The problem with the validation check (we are talking JobServer)  is that it checks
    every file in the directory. Autodesk should change it to just check the mentioned
    file in the .vcet.config-file and not any relatives. Iâ€™ve been struggling the
    whole day and the reason was a dll from a third party supplier that I needed.


    By the way, thanks for your program, it helped me in the right direction, after
    8 hours I feel relieved.


    /Per'
- author: Doug Redmond
  email: ''
  ip: 72.52.96.9
  url: http://profile.typepad.com/6p0120a5728249970b
  date: '2011-06-14 14:20:28'
  body: 'The .NET framework is what is pulling in all the referenced DLLs.  I don''t
    think JobProcessor.exe itself is trying to load every file in the directory.


    Anyway, good to know things are working for you now.'
- author: Tom
  email: tmccar@gmail.com
  ip: 167.236.248.70
  url: ''
  date: '2011-10-17 18:06:45'
  body: "\" Is your project using .NET 3.5 or earlier? \"...\n  How can I check this?\n\
    \nTom"
- author: Doug Redmond
  email: ''
  ip: 72.52.96.9
  url: http://profile.typepad.com/6p0120a5728249970b
  date: '2011-10-18 07:53:38'
  body: <a href="http://justonesandzeros.typepad.com/blog/2011/02/net-40.html">http://justonesandzeros.typepad.com/blog/2011/02/net-40.html</a>
- author: Tom
  email: tmccar@gmail.com
  ip: 167.236.248.70
  url: ''
  date: '2011-10-18 17:28:31'
  body: Cool, thanks
- author: Mike Collins
  email: Michael.Collins2@thyssenkrupp.com
  ip: 207.148.216.68
  url: ''
  date: '2012-03-29 09:45:35'
  body: 'Hi Doug,


    I am trying to build the PropertyPageSample app.  I am getting the "Error loading
    extension PropertyPageSample" error on starting Vault.


    I tried running the Load Tester utility, and it said that it could not find the  Autodesk.Connectivity.Extensibility.Framework
    version 16.0.56.200.  I checked my project References and I had that DLL, but
    it was version 16.1.58.0.


    Is that really the problem?  How should I approach fixing it?'
- author: Doug Redmond
  email: ''
  ip: 72.52.96.9
  url: http://profile.typepad.com/6p0120a5728249970b
  date: '2012-03-30 07:30:09'
  body: "Hotfixes should not affect API applications.  They don't have strong names,\
    \ so you should be able to swap in different versions without causing errors.\n\
    \nAnyway, post your app to the Vault customization discussion group and I'll take\
    \ a look: \n<a href=\"http://forums.autodesk.com/t5/Autodesk-Vault-Customization/bd-p/301\"\
    >http://forums.autodesk.com/t5/Autodesk-Vault-Customization/bd-p/301</a>"
- author: Mike Collins
  email: Michael.Collins2@thyssenkrupp.com
  ip: 207.148.216.68
  url: ''
  date: '2012-03-30 09:47:37'
  body: Ok thanks.  I have created a post there.
- author: Iwan van Wijk
  email: iwan.van.wijk@greenock.eu
  ip: 80.113.0.121
  url: ''
  date: '2012-10-03 08:16:34'
  body: 'Hello Doug,


    Are you making a test loader for Vault 2013? I have used the test loader for Vault
    2012 a couple of times.'
- author: Doug Redmond
  email: ''
  ip: 8.19.13.19
  url: http://profile.typepad.com/6p0120a5728249970b
  date: '2012-10-03 08:29:28'
  body: "Vault 2013 has an error logging feature.  So, I'm hoping that a 2013 test\
    \ loader isn't needed.  \n\n<a href=\"http://justonesandzeros.typepad.com/blog/2012/07/extension-loading-error-logging.html\"\
    >http://justonesandzeros.typepad.com/blog/2012/07/extension-loading-error-logging.html</a>\n\
    \n-----"
