comments:
- author: Pierre
  email: pierrega@consortech.com
  ip: 207.96.162.98
  url: ''
  date: '2014-10-27 14:39:07'
  body: 'Hello Doug,


    How can I access from my extension code to the specific settings added in my vcet.config
    file.


    Thanks,

    Pierre'
- author: Doug Redmond
  email: ''
  ip: 132.188.64.149
  url: http://profile.typepad.com/6p0120a5728249970b
  date: '2014-10-27 16:07:55'
  body: 'There is no easy way to read that data.  The vcet.config is for the plug-in
    loader framework.  If your app wants to store settings, I suggest doing it in
    another file.

    -----'
