assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d13defa3970c-800wi
  filename: image_53563.jpg
  alt_text: Autocad_api_comparison
  title: Autocad_api_comparison
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d13df190970c-800wi
  filename: image_702031.jpg
  alt_text: Autocad_api_comparison
  title: Autocad_api_comparison
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d13df48b970c-800wi
  filename: image_362332.jpg
  alt_text: Autocad_api_comparison
  title: Autocad_api_comparison
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c7b486d5970b-800wi
  filename: image_994145.jpg
  alt_text: Autocad_api_comparison
  title: Autocad_api_comparison
  asset_type: image
