assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb08c662b0970d-500wi
  filename: image_76667.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d14eddd0970c-800wi
  filename: image_130183.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb08c659d8970d-800wi
  filename: image_939020.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1ac0ddb970c-450wi
  filename: image_458366.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb08c659e6970d-450wi
  filename: image_347794.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1ac0dea970c-800wi
  filename: image_295195.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1ac0e08970c-450wi
  filename: image_435829.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c821cdb9970b-450wi
  filename: image_624395.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb08c65a27970d-450wi
  filename: image_795763.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1ac0e1a970c-450wi
  filename: image_929061.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1ac1c06970c-800wi
  filename: image_121222.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1ac0e2d970c-800wi
  filename: image_872426.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c821cddb970b-800wi
  filename: image_986149.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c821d5c2970b-800wi
  filename: image_222017.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1ac1a68970c-400wi
  filename: image_947708.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1ac1a9b970c-800wi
  filename: image_675189.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb08c66526970d-700wi
  filename: image_247000.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c821d758970b-800wi
  filename: image_521141.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c82250ab970b-800wi
  filename: image_293560.jpg
  alt_text: Development_tools
  title: Development_tools
  asset_type: image
