assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c842aef4970b-150wi
  filename: image_705391.jpg
  alt_text: Cloud9_logo
  title: Cloud9_logo
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1cd6a08970c-800wi
  filename: image_377143.jpg
  alt_text: Cloud9_logo
  title: Cloud9_logo
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1cd6d5b970c-450wi
  filename: image_627578.jpg
  alt_text: Cloud9_logo
  title: Cloud9_logo
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1cd704e970c-800wi
  filename: image_774778.jpg
  alt_text: Cloud9_logo
  title: Cloud9_logo
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb08e7460f970d-800wi
  filename: image_921746.jpg
  alt_text: Cloud9_logo
  title: Cloud9_logo
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1cd9c7a970c-800wi
  filename: image_555314.jpg
  alt_text: Cloud9_logo
  title: Cloud9_logo
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c8436845970b-800wi
  filename: image_952495.jpg
  alt_text: Cloud9_logo
  title: Cloud9_logo
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb08e75429970d-500wi
  filename: image_654638.jpg
  alt_text: Cloud9_logo
  title: Cloud9_logo
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb08e75934970d-800wi
  filename: image_420730.jpg
  alt_text: Cloud9_logo
  title: Cloud9_logo
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb08e75ced970d-800wi
  filename: image_120338.jpg
  alt_text: Cloud9_logo
  title: Cloud9_logo
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1cdb17d970c-800wi
  filename: image_572318.jpg
  alt_text: Cloud9_logo
  title: Cloud9_logo
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c8437d14970b-800wi
  filename: image_861754.jpg
  alt_text: Cloud9_logo
  title: Cloud9_logo
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1cdb467970c-800wi
  filename: image_846762.jpg
  alt_text: Cloud9_logo
  title: Cloud9_logo
  asset_type: image
