assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb09801518970d-500wi
  filename: image_612886.jpg
  alt_text: Acad2015_dev_env
  title: Acad2015_dev_env
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb09801594970d-500wi
  filename: image_354861.jpg
  alt_text: Acad2015_dev_env
  title: Acad2015_dev_env
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c8dd2c2e970b-800wi
  filename: image_566505.jpg
  alt_text: Acad2015_dev_env
  title: Acad2015_dev_env
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01bb0980573a970d-800wi
  filename: image_887691.jpg
  alt_text: Acad2015_dev_env
  title: Acad2015_dev_env
  asset_type: image
