assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0278807ab535200d-800wi
  filename: image_769262.jpg
  alt_text: Development_environment
  title: Development_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02e860fdc9d2200d-800wi
  filename: image_355645.jpg
  alt_text: Development_environment
  title: Development_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0282e1534905200b-400wi
  filename: image_57660.jpg
  alt_text: Development_environment
  title: Development_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02e860e6cd62200b-800wi
  filename: image_858049.jpg
  alt_text: Development_environment
  title: Development_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02c8d3d01dde200c-800wi
  filename: image_590952.jpg
  alt_text: Development_environment
  title: Development_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02e860fdca07200d-800wi
  filename: image_858036.jpg
  alt_text: Development_environment
  title: Development_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02e860e6ce0a200b-800wi
  filename: image_615724.jpg
  alt_text: Development_environment
  title: Development_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02e860fdca2b200d-800wi
  filename: image_45203.jpg
  alt_text: Development_environment
  title: Development_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02c8d3d01e36200c-800wi
  filename: image_428873.jpg
  alt_text: Development_environment
  title: Development_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02c8d3d01e57200c-500wi
  filename: image_530000.jpg
  alt_text: Development_environment
  title: Development_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02e860fdca5c200d-500wi
  filename: image_394385.jpg
  alt_text: Development_environment
  title: Development_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02e860e6ce1b200b-500wi
  filename: image_847071.jpg
  alt_text: Development_environment
  title: Development_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02e860e6cf36200b-800wi
  filename: image_805372.jpg
  alt_text: Development_environment
  title: Development_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02c8d3d01f64200c-800wi
  filename: image_142142.jpg
  alt_text: Development_environment
  title: Development_environment
  asset_type: image
