assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad37c9647200d-800wi
  filename: image_296885.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad37c5db1200d-500wi
  filename: image_520825.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad39c437c200b-800wi
  filename: image_692958.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad3566c95200c-800wi
  filename: image_700340.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad39c46ac200b-800wi
  filename: image_763757.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad37c60d2200d-800wi
  filename: image_45036.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad3566eb6200c-800wi
  filename: image_490724.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad3566f35200c-800wi
  filename: image_13947.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad3566f65200c-800wi
  filename: image_81414.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad39c49e5200b-800wi
  filename: image_633441.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad39c4a5b200b-800wi
  filename: image_82158.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad37c64e2200d-800wi
  filename: image_281822.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad35670bb200c-800wi
  filename: image_992604.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad3567123200c-800wi
  filename: image_449580.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad37c659f200d-800wi
  filename: image_405860.jpg
  alt_text: AWSCloud9_logo_color_200x200
  title: AWSCloud9_logo_color_200x200
  asset_type: image
