assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad3a88905200d-800wi
  filename: image_111848.jpg
  alt_text: Webhooks-api-blue
  title: Webhooks-api-blue
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad3a889a9200d-250wi
  filename: image_361409.jpg
  alt_text: Webhooks-api-blue
  title: Webhooks-api-blue
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad38288c9200c-800wi
  filename: image_755716.jpg
  alt_text: Webhooks-api-blue
  title: Webhooks-api-blue
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b022ad3c83574200b-800wi
  filename: image_600856.jpg
  alt_text: Webhooks-api-blue
  title: Webhooks-api-blue
  asset_type: image
