assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b025d9b363a42200c-800wi
  filename: image_414072.jpg
  alt_text: Shutterstock_699442621
  title: Shutterstock_699442621
  asset_type: image
