assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02788058d5f1200d-800wi
  filename: image_125888.jpg
  alt_text: Ransition
  title: Ransition
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0282e13172ae200b-800wi
  filename: image_359370.jpg
  alt_text: Ransition
  title: Ransition
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0282e1317255200b-800wi
  filename: image_972238.jpg
  alt_text: Ransition
  title: Ransition
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0282e13172a1200b-800wi
  filename: image_465967.jpg
  alt_text: Ransition
  title: Ransition
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0282e1317308200b-800wi
  filename: image_660848.jpg
  alt_text: Ransition
  title: Ransition
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b026bdec4ff6b200c-800wi
  filename: image_737655.jpg
  alt_text: Ransition
  title: Ransition
  asset_type: image
