assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b026bdef0e4ea200c-800wi
  filename: image_231199.jpg
  alt_text: Vs_environment
  title: Vs_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b026bdef0e548200c-800wi
  filename: image_31873.jpg
  alt_text: Vs_environment
  title: Vs_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b026bdef0e586200c-800wi
  filename: image_271198.jpg
  alt_text: Vs_environment
  title: Vs_environment
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02788048bdb7200d-800wi
  filename: image_960490.jpg
  alt_text: Vs_environment
  title: Vs_environment
  asset_type: image
