assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0282e1388521200b-800wi
  filename: image_165654.jpg
  alt_text: Title
  title: Title
  asset_type: image
- url: https://images.weserv.nl/?w=500&amp;url=ssl:adndevblog.typepad.com/.a/6a0167607c2431970b0240a4fd6393200b-600wi
  filename: image_95501.jpg
  alt_text: Title
  title: Title
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0282e13887f9200b-800wi
  filename: image_363500.jpg
  alt_text: Title
  title: Title
  asset_type: image
- url: https://capture.heartrails.com/100x100?https://knowledge.autodesk.com/ja/community/article/383726
  filename: image_98872.jpg
  alt_text: Title
  title: Title
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b026bdf05c626200c-500wi
  filename: image_841225.jpg
  alt_text: Title
  title: Title
  asset_type: image
