assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02788039af8f200d-800wi
  filename: image_603652.jpg
  alt_text: Forge-header-smartpattern-5
  title: Forge-header-smartpattern-5
  asset_type: image
