assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0278805f39a5200d-800wi
  filename: image_792561.jpg
  alt_text: With-without-compression
  title: With-without-compression
  asset_type: image
