assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02b751706567200b-800wi
  filename: image_755976.jpg
  alt_text: Applications
  title: Applications
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02b75194b6bc200c-800wi
  filename: image_825104.jpg
  alt_text: Applications
  title: Applications
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02b751706651200b-50wi
  filename: image_366700.jpg
  alt_text: Applications
  title: Applications
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02b7517065cc200b-800wi
  filename: image_913000.jpg
  alt_text: Applications
  title: Applications
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02b75194b81a200c-800wi
  filename: image_433599.jpg
  alt_text: Applications
  title: Applications
  asset_type: image
