assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02c8d3d57421200c-800wi
  filename: image_268144.jpg
  alt_text: Application
  title: Application
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02e860ec2a61200b-800wi
  filename: image_228706.jpg
  alt_text: Application
  title: Application
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02e860ec2a49200b-800wi
  filename: image_179308.jpg
  alt_text: Application
  title: Application
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02e860ebeef1200b-800wi
  filename: image_247327.jpg
  alt_text: Application
  title: Application
  asset_type: image
