assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02c8d3af14c8200d-800wi
  filename: image_934733.jpg
  alt_text: Settings_panel
  title: Settings_panel
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02c8d3af14d5200d-800wi
  filename: image_126124.jpg
  alt_text: Settings_panel
  title: Settings_panel
  asset_type: image
