assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02e860ec2a9d200b-800wi
  filename: image_681610.jpg
  alt_text: Titile
  title: Titile
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02e86103126d200d-500wi
  filename: image_233742.jpg
  alt_text: Titile
  title: Titile
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b02e860ec2aaa200b-320wi
  filename: image_818792.jpg
  alt_text: Titile
  title: Titile
  asset_type: image
