comments:
- author: Abhishek Singhal
  email: abhi.singhal@gmail.com
  ip: 122.161.126.137
  url: ''
  date: '2009-10-19 18:41:19'
  body: "Brian\n\nThe class handout gives an excellent overview of what is achievable\
    \ and what to expect with the drawing API that existed at that time.\n\nHowever,\
    \ many new features have been added since then and one of the important ones to\
    \ me is the ability to add balloons.\n\nI am trying to build an application where\
    \ drawings will be created automatically. In our case, the same assembly is used\
    \ in several drawings each of which focuses on a different part of the assembly.\
    \ The BOM of each drawing is available separately and the application knows which\
    \ componentoccurences in the tree correspond to those items.\n\nOk. Now the questions.\n\
    \n1. Is it possible to customize the auto balloon feature (present in Inventor\
    \ UI) through the API to mark only the items of interest.\n\n2. If the answer\
    \ to above question is no, I guess the only solution is for the application to\
    \ actually make the balloons for the items of interest through API. \nIn that\
    \ case, would there be a sample available which can show what are the issues to\
    \ take care (placement etc.) during auto ballooning ?\n\nThanks and Regards\n\
    Abhishek"
- author: Don Wen
  email: dwen999@yahoo.com
  ip: 204.244.252.153
  url: ''
  date: '2009-10-23 19:59:16'
  body: Thanks Brian. Just for others info, the downloaded file has to be renamed
    as a .zip file to open it.
