comments:
- author: Jens Bejer Pedersen
  email: jbp@cdlight.dk
  ip: 87.104.234.146
  url: http://www.cdlight.dk
  date: '2010-09-23 09:20:49'
  body: 'Hi Brian


    A couple of comments on the PDF Document:


    The first link on page 5 points to a file in the local users temporary internet
    files and of gives an error when clicked.


    In several of the code examples You use the Inventor Application as _InvApplication
    but I think You intended to use ThisApplication since You use the VBA Environment.


    In general You use a mixed mode for writing Object.Method accessors, either using
    the :: as in C++ or just using the . as in VB and C# (and in all the VBA code
    examples), I would recommend to use either only one of these conventions or at
    least give an explanation when :: is used the first time (Page 16) as this is
    after the first code examples.


    I would like You to extend the document with some examples about (Model) Parameters
    and Properties, how to get, Query and Set these entities.


    Regards,

    Jens Bejer Pedersen'
- author: jakubd
  email: jakubd@pspsolution.pl
  ip: 83.8.228.62
  url: http://www.pspsolution.pl
  date: '2010-10-13 08:46:07'
  body: 'Hi Brian


    I need help with vba script in inventor for one of Our customers.


    Can You please contact me to my email ?


    Best Regards


    Jakub D.

    -----'
