comments:
- author: Jhon Hermosa
  email: larry.hermosa@enka.com.co
  ip: 190.248.13.106
  url: http://www.youtube.com/user/jhonlarry?feature=watch
  date: '2012-09-20 17:15:04'
  body: 'Its like a macro that is post in <a href="http://www.youtube.com/watch?v=qafEUbXBCUI&list=UUs9IE2l3HNZRkcHztjhsoDw&index=16&feature=plcp.">http://www.youtube.com/watch?v=qafEUbXBCUI&list=UUs9IE2l3HNZRkcHztjhsoDw&index=16&feature=plcp.</a>

    -----'
