comments:
- author: Sergio Duran
  email: sduran@solidcad.ca
  ip: 24.150.10.151
  url: ''
  date: '2013-07-18 19:27:30'
  body: I tested it and found out that there is no way to see properties. Am I correct?
- author: Sergio Duran
  email: sduran@solidcad.ca
  ip: 24.150.10.151
  url: ''
  date: '2013-07-18 19:35:39'
  body: Does it have a link with the Inventor file once you uploaded it? I uploaded
    an Inventor part, then I modified the part in Inventor but when I went back to
    Autodesk Configurator 360, my Inventor file didn't update. Is there any way to
    update designs on Autodesk Configurator 360 after having changed them in Inventor?
- author: Wayne Brill
  email: wayne.brill@autodesk.com
  ip: 72.52.96.18
  url: ''
  date: '2013-07-18 19:59:55'
  body: 'Hi Sergio,


    I believe you are asking if Inventor iProperties are available in C360. They are
    not displayed by C360 that I have seen. It just uses parameters.'
- author: Wayne Brill
  email: wayne.brill@autodesk.com
  ip: 72.52.96.18
  url: ''
  date: '2013-07-18 20:03:02'
  body: 'Hi Sergio,


    There is not a link to the local Inventor File once you have uploaded it. I believe
    you need to create a new design and delete the old one. (that is what I did).
    I am not an expert on C360 however.'
- author: Wayne Brill
  email: wayne.brill@autodesk.com
  ip: 72.52.96.18
  url: ''
  date: '2013-07-18 21:30:39'
  body: "Hi Sergio,\n\nHere is a suggestion:\n \" If I understand what you’re looking\
    \ for -- It does not show iProperties directly at this time. You can set up a\
    \ parameter to get the value of the property, using iLogic, perhaps with an “event\
    \ trigger”, and then display the parameter in Configurator 360 as read-only. You\
    \ need to use the “Parameters” tab (click on the Pencil icon). Make sure the read-only\
    \ check-box “takes” … it’s temperamental. \" \n\nAlso questions on C360 can be\
    \ posted to this newsgroup:\n <a href=\"https://forums.autodesk.com/t5/Autodesk-Configurator-360/bd-p/3541\"\
    >https://forums.autodesk.com/t5/Autodesk-Configurator-360/bd-p/3541</a>\n\n\n\
    -----"
