comments:
- author: Alex
  email: ajshmidt@gmail.com
  ip: 71.13.134.98
  url: ''
  date: '2014-02-18 14:40:35'
  body: "Hello everyone!\n \nI`m writting an addin for inventor 2014 and I`m not sure\
    \ how to make addin to disapear from the ribbon when user unchecks the unload\
    \ checkbox in addin manager? and vice versa to appear when user check the box?\n\
    \ \nAny help is appreciated.\n \nThank you,\nAlex"
- author: Philippe Leefsma
  email: ''
  ip: 92.105.24.95
  url: http://profile.typepad.com/6p0167638460d1970b
  date: '2014-02-18 15:07:29'
  body: "That question is unrelated to the topic of this post. Please open a new thread\
    \ on the Inventor Customization forum: \n<a href=\"http://forums.autodesk.com/t5/Inventor-Customization/bd-p/120\"\
    >http://forums.autodesk.com/t5/Inventor-Customization/bd-p/120</a>\n\nThanks,\n\
    Philippe.\n-----"
