comments:
- author: tang
  email: Tyemoonlight@163.com
  ip: 115.192.185.61
  url: ''
  date: '2012-07-17 18:53:22'
  body: 'Hello！I come from China.Now,I am a student and a trainee

    in my teacher''s company.I am studying how to make dwg file

    cheched up in website.A few days ago,I found Barbara''blog about idrop in CSDN.It
    works.Here,I very appreciate your share.But the dwg file in web is very vague.So,I
    came to ask help.Could you hlep me?Please inform me if you are willing to help
    me. My Email address is Tyemoonlight@163.com. Thank you very much!'
- author: Xiaodong Liang
  email: xiaodong.liang@autodesk.com
  ip: 125.98.160.4
  url: ''
  date: '2012-07-19 02:58:10'
  body: 'hi tang,


    Can I suggest you update the orignal blog in CSDN with your comment? The blogger
    Barbara would be able to help when she has time.


    Regards,

    Xiaodong'
- author: tang
  email: Tyemoonlight@163.com
  ip: 115.193.162.124
  url: ''
  date: '2012-07-19 21:02:31'
  body: Thank you very much!I have contacted her with my comcment.She is vrey warm-hearted.Although
    the problem isn't soved,I have know this way is not acceccible.
- author: tang
  email: Tyemoonlight@163.com
  ip: 115.193.162.124
  url: ''
  date: '2012-07-19 21:02:44'
  body: So I have to find other ways to work out it.Here,Thank you and Barbara Han
    again!
- author: Luigi Trabacchin
  email: trabacchin.luigi@gmail.com
  ip: 94.38.248.38
  url: ''
  date: '2015-02-10 15:34:59'
  body: hello Xiaodong, this example doesn't work for me, i need a late binding, i'm
    not able to cast the AddinAutomation to the interface i've implemented, only to
    call methods with late binding (declaring a variable with dynamic) or i get a
    com exception E_NOINTERFACE ... any idea on why ?
- author: Paul Schüpbach
  email: paul.schuepbach@morecam.ch
  ip: 88.84.25.36
  url: http://www.sparepartsplace.com
  date: '2015-07-09 04:48:53'
  body: 'Ciao Luigi,


    in the AddIn''s VS Project Settings enable ''Register for COM-Interop'' and it
    will work...


    Best, Paul'
- author: Søren Nørgaard
  email: ''
  ip: 91.194.94.35
  url: http://profile.typepad.com/6p01bb0917c153970d
  date: '2016-06-28 00:14:09'
  body: "Hi.\nReally good tutorial. \nI have a small problem though. i followed the\
    \ above, but when i have a method with a return type on the addin side that i\
    \ call from the exe side i get an error. it says that it cannot convert the returned\
    \ type into the type that i use. \ni have tried with different return types but\
    \ same error every time."
- author: Tom Kennedy
  email: thomaskennedy@me.com
  ip: 185.81.194.4
  url: ''
  date: '2016-10-18 02:18:55'
  body: 'Great tutorial.

    Has anybody managed to return the correct type from the addin?

    I am using an iLogic rule to pass the SharedVariable interface to the addin -
    this works OK.

    From my external application I then pull in the interface from the addin but it
    is returned as Com__Object which doesn''t cast into ISharedVariable.

    Thanks, Tom'
- author: Rao
  email: vrao@hubbell.com
  ip: 10.13.30.152
  url: ''
  date: '2017-01-11 05:15:21'
  body: "Hi,\n\nI tried the above code, but having issue in casting the COM object\
    \ to AutomationInterface.\n\nCould someone help me.\n\nThanks \nRao"
- author: Valerio Pittavino
  email: info@dnsistemi.com
  ip: 88.147.26.98
  url: http://www.dnsistemi.com
  date: '2019-12-06 21:33:48'
  body: 'Hi,

    the chat is old but I had the same problem yesterday and for me is a problem register
    the addin as com-interop.

    I have to comunicate events between differents addins and i solved in this way:

    I have 1 addin ("server") that must is the source of datas (for me is the login
    to my web site)

    I have n addins that are the clients

    The server provide an object of type xxx by Automation property

    The client register the server automation in a dynamic variable and calls a method
    "RegisterClient (dynamic client)" that has 1 dynamic parameter that is an object
    in the "client" Addin

    When the server have to launch an event in the clients it will iterate the client
    list and call a method in the client object that fire the event.


    This way works why I use the dynamic type that C# tries to solve in runtime. The
    bad thing is that you can''t cast this object else you get an invalid cast exception
    and that you haven''t the intellisense during coding.


    I hope this will be usefull.


    Thanks

    Valerio Pittavino

    -----'
