comments:
- author: Daniel Balogh
  email: daniel.balogh@eppco.at
  ip: 91.141.3.3
  url: http://www.eppco.at
  date: '2014-09-26 21:54:08'
  body: 'Hello Wayne,


    I''m trying to run ETO on a german Inventor 2015 Professional. The Addin is listed,
    but stops immediately after loading. I''ve already been working with it, but it
    just stopped to work for no known reason. I uninstalled ETO / reinstalled it with
    no luck.

    Is there any known issue with german releases of Inventor / Windows7? Already
    installed ETO SP1 (ETO8100_x64.msp) but did not help.

    We are ADSK-Partner but in Subscriptioncenter the ETO server 2013 R2 the newest
    one to download. I found hints there is a 2015 release as well but I have no idea,
    where to download it...

    Any hints were appreciated.

    BR,

    Daniel'
- author: Daniel Balogh
  email: daniel.balogh@eppco.at
  ip: 91.141.3.3
  url: http://www.eppco.at
  date: '2014-09-26 22:35:38'
  body: 'Ok... I found the problem... My inventor isn''t installed on the system drive
    and (therefore...?) the intent.config was not copied in the Inventor bin folder.
    So the addin was unable to load...

    BR,

    Daniel


    The question of the download location for ETO Server 2015 is still open :)'
- author: Wayne Brill
  email: wayne.brill@autodesk.com
  ip: 132.188.72.146
  url: ''
  date: '2014-09-29 15:22:25'
  body: 'Hi Daniel,


    If you are an ADN member you can download from the ADN site. If you use subscription
    center please ensure your subscription is active.


    Thanks,

    Wayne

    -----'
