comments:
- author: Nik Barbour
  email: nbarbour@joy.co.uk
  ip: 83.100.246.8
  url: ''
  date: '2013-04-19 00:55:51'
  body: Thanks for this - it is exactly what I was looking for.
- author: Ben
  email: bwinding@kovabc.com
  ip: 184.71.132.26
  url: ''
  date: '2013-09-16 14:51:44'
  body: 'Hi thanks for this, excatly what I''m looking for. But I copied and pasted
    the code as a module in Inventor 2012, but I''m getting an error.


    "user defined type not defined"


    Does this sample work? Or do I need to enable the Microsoft Sctipting Runtime?


    Cheers,

    Ben'
- author: Adam Nagy
  email: ''
  ip: 86.31.122.37
  url: http://profile.typepad.com/1236098880s16462
  date: '2013-09-17 06:37:04'
  body: "Hi Ben,\n\nYes, this specific solution is using the Dictionary class from\
    \ Microsoft Scripting Runtime. So inside VBA you can simply go to \"Tools >> References...\"\
    , search for \"Microsoft Scripting Runtime\" and tick the box next to it.\n\n\
    Cheers,\nAdam \n-----"
