comments:
- author: noontz
  email: steffen@dyhr-nielsen.dk
  ip: 178.157.252.114
  url: ''
  date: '2013-03-06 01:55:29'
  body: 'WOW..  Thanks.. Implemented this in C# and works as a charm.

    Babara : You are "most wanted person" over at the folks making the Inventor SDK
    help files.   ( If there is anybody there? )'
- author: Mario
  email: mario.lung@westcam.at
  ip: 195.149.220.30
  url: http://www.westcam.at
  date: '2013-08-07 06:39:45'
  body: "Hi,\nany Problems with this in Inventor 2014?\n\nthis line brings a error\
    \ \n\nSet transientObj = app.TransientObjects\n\nthx\nMario\n\nP.s. i have a ADN\
    \ Subscription also\n-----"
