comments:
- author: maxim teleguz
  email: m.teleguz1@gmail.com
  ip: 50.230.139.34
  url: https://pumps.netzsch.com/us/
  date: '2019-10-16 08:03:54'
  body: can you create a addin for this please?
- author: Chandra shekar G
  email: chandra.shekar.g@autodesk.com
  ip: 202.74.99.101
  url: http://www.autodesk.com
  date: '2019-10-23 02:49:49'
  body: 'Hi Maxim,


    Addin can be downloaded from below link.


    <a href="https://myshare.autodesk.com/:f:/g/personal/chandra_shekar_g_autodesk_com/Ev1N4_N2H01Hrt3WbX15d9kB397M-dACSXlN6Ei4gABgLw?email=m.teleguz1%40gmail.com&e=djpRgE">https://myshare.autodesk.com/:f:/g/personal/chandra_shekar_g_autodesk_com/Ev1N4_N2H01Hrt3WbX15d9kB397M-dACSXlN6Ei4gABgLw?email=m.teleguz1%40gmail.com&e=djpRgE</a>


    Thanks and regards,

    Chandra shekar G'
- author: Chandra shekar G
  email: chandra.shekar.g@autodesk.com
  ip: 202.74.99.101
  url: http://www.autodesk.com
  date: '2019-10-23 02:53:34'
  body: 'Hi Maxim,


    Addin source code can be downloaded from below link.


    <a href="https://myshare.autodesk.com/:f:/g/personal/chandra_shekar_g_autodesk_com/Ev1N4_N2H01Hrt3WbX15d9kB56qw-r9fAk757RcMwjGBBg?e=eqtluh">https://myshare.autodesk.com/:f:/g/personal/chandra_shekar_g_autodesk_com/Ev1N4_N2H01Hrt3WbX15d9kB56qw-r9fAk757RcMwjGBBg?e=eqtluh</a>


    Thanks and regards,

    Chandra shekar G

    -----'
