comments:
- author: Reg Hasell
  email: rhasell@gmail.com
  ip: 124.170.183.21
  url: ''
  date: '2018-04-12 17:49:31'
  body: "Hi\n\nThank you, I have made a small change, as for some reason or other\
    \ the version did not work, and all my exports were @AC1032 (Ver2018) Placing\
    \ the version at the top of the options list worked?\n\nIf oDocument.DocumentType\
    \ = kPartDocumentObject Or oDocument.DocumentType = kAssemblyDocumentObject Then\n\
    \                'Acad 2010 = 29\n\t\t'Acad 2013 = 31\n\t\t'Acad 2018 = 32\n\t\
    \toOptions.Value(\"DwgVersion\") = 31\n\t\toOptions.Value(\"Solid\") = True\n\
    \                oOptions.Value(\"Surface\") = False\n                oOptions.Value(\"\
    Sketch\") = False\n        End If\n\nRegards\nReg."
- author: Mark Kok
  email: mkok@ambaflex.com
  ip: 5.178.22.59
  url: ''
  date: '2020-11-23 22:22:02'
  body: 'Is there also a way to use a template .dwg for exporting a 3D dwg?

    -----'
