comments:
- author: David
  email: vnsharifi@gmail.com
  ip: 216.185.64.78
  url: ''
  date: '2012-12-11 10:50:24'
  body: "Hello Balaji.\nThanks for the Post. \nCan you please show us(with code )\
    \ how  to change a none rectangular paperspace viewport customscale and view center\
    \ , when user is in model space .\nI have several layout tabs and on each layout\
    \ have several non rectangular viewports and need to change view center and zoomfactor\
    \ of just one of them.\nI am struggle for one week.\nThanks\nDavid\n\n\n-----"
