comments:
- author: Oleg
  email: fattyhallex@gmail.com
  ip: 92.100.91.18
  url: ''
  date: '2012-08-01 07:16:55'
  body: 'Thanks for the good work, Philippe!

    This code is working like a sharm for me,


    Regards,


    Oleg'
- author: Philippe Leefsma
  email: Philippe.Leefsma@autodesk.com
  ip: 95.172.68.148
  url: ''
  date: '2012-09-20 08:47:14'
  body: No problem, you're welcome;)
- author: Carl
  email: Carl.Golenberg@brownconsulting.com.au
  ip: 125.7.48.146
  url: ''
  date: '2014-03-12 18:01:39'
  body: hmm. everywhere you have Layout, intellisense asks for PlotSettings in my
    studio...
- author: Oscar T
  email: ''
  ip: 46.136.38.182
  url: http://profile.typepad.com/6p01bb0987522b970d
  date: '2017-03-25 13:11:01'
  body: "May be I'm wrong but I think there could be a typo. Shouldn't be the comparer\
    \ \">=\" be replaced with \"<\" in the previous code? In the section:\n\n    \
    \          //Check if 90Â°Rot will fit, otherwise check next media\n          \
    \    if(mediaPageHeight < pageWidth ||\n                 mediaPageWidth <b> >=\
    \ </b> pageHeight)\n-----"
