comments:
- author: Alexander Rivilis
  email: ''
  ip: 91.142.169.221
  url: http://profile.typepad.com/alexanderrivilis
  date: '2012-08-10 00:31:37'
  body: 'Double post:

    <a href="http://adndevblog.typepad.com/autocad/2012/08/removing-an-application-from-the-appid-table-1.html">http://adndevblog.typepad.com/autocad/2012/08/removing-an-application-from-the-appid-table-1.html</a>

    <a href="http://adndevblog.typepad.com/autocad/2012/08/removing-an-application-from-the-appid-table.html">http://adndevblog.typepad.com/autocad/2012/08/removing-an-application-from-the-appid-table.html</a>

    ?'
- author: Balaji
  email: ''
  ip: 115.112.233.72
  url: http://profile.typepad.com/6p016303198bdc970d
  date: '2012-08-10 05:31:49'
  body: 'Thank you :)

    I removed the duplicate post.

    -----'
