comments:
- author: Rajibyadev123
  email: debendramahalik@yahoo.in
  ip: 122.50.245.188
  url: http://www.automateandvalidate.com
  date: '2012-12-14 07:13:23'
  body: 'I see absolutely nothing really difficult to apply the intents: The certification
    webserver need its very own private as well as public key pairs. Then chances
    are you need to create.'
- author: Augusto Goncalves
  email: ''
  ip: 187.37.85.200
  url: http://profile.typepad.com/6p0168e7e7c9dd970c
  date: '2012-12-14 08:21:14'
  body: 'Hi,


    Not sure what you mean here...can you clarify?


    Regards,

    Augusto Goncalves'
- author: Ben
  email: benkoshy@hotmail.com
  ip: 165.228.230.183
  url: ''
  date: '2016-03-02 03:32:42'
  body: 'Hello thank you for your excellent article!


    The crpto program..."requires reference to Windows Form, which can affect AutoCAD
    console;"


    How will a windows forms reference affect the autocad console? Are there any work-around
    solutions?'
- author: Augusto Goncalves
  email: ''
  ip: 187.106.222.63
  url: http://profile.typepad.com/6p0168e7e7c9dd970c
  date: '2016-03-02 03:54:30'
  body: "Hi Ben,\n\nIndeed AutoCAD Console cannot have windows Forms, it's a console\
    \ application... therefore use these references will make the plugin DLL incompatible.\
    \ \n\nRegards,\nAugusto Goncalves"
- author: Keith Brown
  email: ''
  ip: 173.165.36.77
  url: http://profile.typepad.com/keithbrown1
  date: '2016-03-02 08:20:17'
  body: 'If you don''t use their dialog then I believe that you can use it without
    Systems.Windows.Forms.


    For instance, just check to see if the product is licensed and if not then cancel
    out of the console.  You could create a separate .exe to license the application.'
- author: Ben
  email: benkoshy@hotmail.com
  ip: 165.228.230.183
  url: ''
  date: '2016-03-03 14:47:44'
  body: thanks Keith that will come in very useful
- author: Sam Porter
  email: samporter21@gmail.com
  ip: 70.48.109.117
  url: ''
  date: '2017-08-24 09:24:00'
  body: 'If you''re looking to protect an AutoCAD app, you might want to check out
    Quick License Manager by Soraco Technologies at <a href="https://soraco.co">https://soraco.co</a>



    -----'
