comments:
- author: Alexander Rivilis
  email: ''
  ip: 81.95.185.60
  url: http://profile.typepad.com/rivilis1964
  date: '2012-10-02 13:35:45'
  body: 'Hi, Philippe!

    As I remember acdbmgd.lib export function LoadMangedDll. That is why code may
    be simpler: <a href="http://forums.autodesk.com/t5/Autodesk-ObjectARX/netload-in-arx/m-p/2191113#M24126">http://forums.autodesk.com/t5/Autodesk-ObjectARX/netload-in-arx/m-p/2191113#M24126</a>

    -----'
