comments:
- author: Fenton Webb
  email: fenton.webb@autodesk.com
  ip: 8.19.13.19
  url: http://adn.autodesk.com
  date: '2012-07-02 19:12:06'
  body: "Extra Notes: \n\n1) Since RealDWG 2012 the security attributes are not needed\n\
    2) Visual Studio versions have changed to Visual Studio 2010"
- author: Carl
  email: Carl.Golenberg@brownconsulting.com.au
  ip: 125.7.48.146
  url: ''
  date: '2013-12-18 14:21:15'
  body: Hi there! I'm trying to build an in-house batch plotter utility - I would
    like it to run outside of Autocad, but I CAN have Autocad installed - I don't
    need a full RealDWG solution. Is this possible or does external access have to
    be RealDWG?
- author: Peter
  email: peterwilliamsz@hotmail.com
  ip: 72.1.105.114
  url: ''
  date: '2016-05-22 13:48:42'
  body: 'RealDWG is NOT an option. The pricing is absolutely ridiculous!


    AutoCAD is now affordable but without a DWG manipulator (independently of AutoCAD),
    managing a large number of files is impractical.


    We need an affordable DWG solution!'
- author: Stephen Preston
  email: ''
  ip: 132.188.64.219
  url: http://profile.typepad.com/stephenpreston
  date: '2016-05-23 16:48:31'
  body: 'Hi Peter,


    I''m not going to argue with your opinion on the price. Either your business model
    gives you an ROI from licensing RealDWG or it doesn''t.


    However, this is now a very old article. RealDWG is still alive and well, but
    we have recently introduced another option - AutoCAD I/O. AutoCAD I/O is AcCoreConsole
    (think headless AutoCAD) running on a server - to which you can submit batch jobs.
    AutoCAD I/O has an advantage over RealDWG, because it can also plot. The service
    is currently in Beta and is therefore free. Eventually, possibly as early as next
    month, Autodesk will announce a pricing model, which will be usage based so you
    only pay for what you expect to use. See <a href="https://developer.autodesk.com/api/autocadio/">https://developer.autodesk.com/api/autocadio/</a>
    for more info.


    Cheers,


    Stephen

    -----'
