comments:
- author: Maxence DELANNOY
  email: maxence.delannoy@wiip.fr
  ip: 92.147.142.39
  url: http://wiip.fr
  date: '2012-11-15 05:34:49'
  body: 'PlotConfigManager.get_StdConfigNames(StdConfiguration.NoneDevice) should
    be used instead of litteral "None"

    -----'
