comments:
- author: Luisa
  email: booboolumpkins@gmail.com
  ip: 208.77.233.190
  url: ''
  date: '2013-01-16 11:55:09'
  body: 3D <a href="http://www.q-cad.com" target="_blank">cad drafting</a> looks complex...
    I've just started interior design classes and I can't wait to get out of 2D modelling
    but 3D drafting looks intimidating! :)
- author: JW
  email: jwadley@meridiansolar.com
  ip: 24.153.157.66
  url: ''
  date: '2015-07-30 08:10:56'
  body: 'How do we navigate to this setting.  The format looks like a registry entry,
    but I am not finding it there.

    -----'
