comments:
- author: Nick G.
  email: gonini_arx@ukr.net
  ip: 37.55.10.213
  url: http://arx.16mb.com/
  date: '2012-06-11 04:23:57'
  body: "Hi, Virupaksha.\nWhat is the sence of your (or may be not your) code.\nThe\
    \ same code is posted here: <a href=\"http://adn.autodesk.com/adn/servlet/devnote?siteID=4814862&id=6844959&linkID=4900509\"\
    >http://adn.autodesk.com/adn/servlet/devnote?siteID=4814862&id=6844959&linkID=4900509</a>\n\
    \nMay be the main reason of this blog is to make adn sources open for everybody?\
    \ :):):) \n1. try to add something new to this code(for example setPlotPaperUnits).\
    \ My default units - MM, but if I select inches's paper size I get result in inches\
    \ (but paper units within print dialog are millimeters)\n2. may be it's time to\
    \ create a useful function from this code :), for example \nbool addLayout(\n\
    ACHAR * wantedLayoutName, // want this name for layout\ndouble viewportWidth,\
    \ // layout's viewport width\ndouble viewportHeight, // layout's viewport height\
    \ \nAcGePoint2d minPtDCS, // min model point for vewport\nAcGePoint2d maxPtDCS,\
    \ // max model point for vewport\nconst ACHAR * printerName, // printer name\n\
    AcDbPlotSettings::PlotPaperUnits paperUnits, // paper units\nconst ACHAR * paperSize,\
    \ // format\nbool landscapeMode, // landscape or book mode\nbool setLocked //\
    \ lock viewport\n)"
- author: haha
  email: sixhit@163.com
  ip: 74.82.35.43
  url: ''
  date: '2018-07-16 21:45:17'
  body: 'sorry,I am not very good at English.I try to use these code fSetPlotMedia()
    to plot DWG,I successfully select plotDevice and Media,but after select,Autocad
    “Fatal Error”.I con''t find the reason of the failure,I''m stuck on  the  question
    a few months.i need help ,thanks.

    -----'
