comments:
- author: RenderMan
  email: rmcadguy@gmail.com
  ip: 24.92.15.133
  url: ''
  date: '2012-07-14 13:01:02'
  body: "FWIW - \n\nThis was posted back on August 9, 2011:\n\n<a href=\"http://www.geospecialling.com/index.php/2011/08/hacking-visual-lisp-ide-to-be-a-little-more-awesome/\"\
    />Hacking Visual Lisp IDE to be a little more awesome!</a>\n\n~RM\n\nYou can also\
    \ find your answers at <a href=\"http://www.theswamp.org/index.php\"><b>TheSwamp</b></a>"
- author: Augusto Goncalves
  email: ''
  ip: 201.58.138.117
  url: http://profile.typepad.com/6p0168e7e7c9dd970c
  date: '2012-07-16 06:14:23'
  body: "Thanks for pointing another source, it's the same idea. \n\nRegards,\nAugusto\
    \ Goncalves"
- author: RenderMan
  email: rmcadguy@gmail.com
  ip: 207.34.120.71
  url: ''
  date: '2012-07-16 07:36:10'
  body: 'You''re welcome, Augusto.


    Just wanted to share that link, as it was posted almost a year earlier. ;)


    In any event... Have you any idea when Autodesk is going to _<i>actually</i>_
    fix this (<i>or other</i>) problem(s) with VLIDE, rather than asking users to
    fix this themselves on another computer?


    Most of us only have one 64Bit work computer, and do not have a spare 32Bit machine
    sitting around with a valid license of AutoCAD installed. Just saying.


    Thanks,


    ~RM'
- author: Darrin Maidlow
  email: dmaidlow@chasmx.com
  ip: 96.53.101.107
  url: http://www.geospecialling.com
  date: '2012-08-07 15:10:57'
  body: 'Thanks for pointing out my post RM.  I appreciate that!  This seems to have
    been corrected in AutoCAD 2013 x64 - at least in Vanilla..  Don''t have a 2013  based
    vertical installed right now though.

    -----'
