comments:
- author: grx
  email: 344675003@qq.com
  ip: 112.120.33.68
  url: ''
  date: '2022-04-23 22:28:50'
  body: Could you show me the AEN1MyCircle's code? Thanks!
- author: Hanauer
  email: gphanauer@gmail.com
  ip: 45.176.226.101
  url: ''
  date: '2022-04-25 06:25:32'
  body: 'I think you find it on DevTV - Ubiquity example.

    <a href="https://adndevblog.typepad.com/autocad/2012/04/devtv-non-com-property-system.html">https://adndevblog.typepad.com/autocad/2012/04/devtv-non-com-property-system.html</a>

    -----'
