comments:
- author: Joshua Hunt
  email: jhunt107@ford.com
  ip: 136.2.1.105
  url: ''
  date: '2014-02-07 13:40:42'
  body: 'How is this different or better than...

    -PURGE

    REGAPPS

    *'
- author: Stephen Preston
  email: ''
  ip: 108.236.113.147
  url: http://profile.typepad.com/stephenpreston
  date: '2014-02-11 21:00:48'
  body: 'Not better - different. For example ...


    - It can be used on AutoCAD versions that don''t have that purge option.


    - It demonstrates how to perform an operation using the API.

    -----'
