comments:
- author: petcon
  email: newton521200@yahoo.com.cn
  ip: 58.49.252.151
  url: ''
  date: '2012-05-17 21:58:17'
  body: "cool.\n kean blog post the similar long ago about p/invoke.\n.net use arx\
    \ function that is AWASOME"
- author: petcon
  email: newton521200@yahoo.com.cn
  ip: 58.49.252.151
  url: ''
  date: '2012-05-17 22:07:18'
  body: "use this magic tool!!\n <a href=\"http://daffodil.codeplex.com/\">http://daffodil.codeplex.com/</a>"
- author: petcon
  email: newton521200@yahoo.com.cn
  ip: 58.49.252.151
  url: ''
  date: '2012-05-17 22:07:52'
  body: 'sorry wrong comment

    -----'
