comments:
- author: Ed Jobe
  email: ''
  ip: 12.178.51.2
  url: http://profile.typepad.com/elj
  date: '2012-07-20 09:31:20'
  body: It works for me if you add settings from the Settings tab of your project's
    Properties.
- author: BJHuffine
  email: bjhuffine@tva.gov
  ip: 152.85.8.33
  url: ''
  date: '2012-07-31 06:12:30'
  body: You're right that the .Net configuration file framework sees the host exe
    for the dll, but there are ways around this rather than using the acad.exe.config.  If
    you just used the acad.exe.config for all your development, things can get pretty
    messy.  You can still use the Visual Studio settings, or the older 2.0 config
    appSettings elements, or even create your own custom elements.  You can even create
    an auxiliary config and merge it with your application config.  And yes all these
    can be retrieved from your dll.  I taught on this at AU last year.  You can look
    for Jason Huffine as the speaker in the AU Online Classes by going to au.autodesk.com.  You
    can also click on this link <a href="http://au.autodesk.com/?nd=class&session_id=9611,">http://au.autodesk.com/?nd=class&session_id=9611,</a>
    but keep in mind you have to sign on to see the information.  It's no big deal
    to register though.  In this I give plenty of examples in the document and I also
    give plenty of sample code with ReadMe.txt files to explain how to setup.  If
    you listen to the presentation, forgive me.  That was my first time talking at
    AU and I was a bit nervous :-).  Hope that helps.
- author: Michael J. Smith
  email: smittynchatt@gmail.com
  ip: 152.85.8.38
  url: ''
  date: '2013-02-15 06:43:59'
  body: Thanks for the great resource Mr. Huffine!!!!
- author: Diego
  email: dscaldaferri@promine.com
  ip: 24.37.53.6
  url: ''
  date: '2015-01-07 08:02:40'
  body: 'How did you read this information?


    Thank you.'
- author: Ben
  email: benkoshy@hotmail.com
  ip: 165.228.230.183
  url: ''
  date: '2016-03-21 04:07:39'
  body: Bloody brilliant Jason!
- author: Ben
  email: benkoshy@hotmail.com
  ip: 165.228.230.183
  url: ''
  date: '2016-03-21 04:19:03'
  body: 'Bad news,


    I added some config settings by going to Visual studio ---> Settings tab of my
    project''s Properties. I then batch built my dll and took the release version
    of my dll onto another computer. *****ERROR****** could not find database at:
    C:\incorrectpath\etc ........oops: I''ll have to change my connection string in
    the config file, which should be located on this new computer (as opposed to the
    computer i developed the plugin on). the connection string should be in the config
    file so i should just change it to point to where the database exists on this
    new computer.


    The config file should be called acad.exe.config. So I go to my Program files
    folder and I find acad.exe.config, and i click on the XML file: but there is no
    connection string.txt copied in there! Where then is this fabled connection string
    located? Acad is obviously storing it somewhere because the Acad error reports
    that the connection string could not be found at that particular path - which
    means that the connection string is being held in an XML file somewhere.


    The question is: Where? Becauase i really need to point it to the new location
    of the database.'
- author: Besanttech1
  email: ''
  ip: 182.65.242.49
  url: http://profile.typepad.com/besanttech1
  date: '2016-04-20 23:39:52'
  body: 'Thanks for sharing informative post. <a href="http://www.traininginsholinganallur.in/qtp-training-in-chennai.html">QTP
    Training in Chennai</a>

    -----'
