comments:
- author: Steven Reed
  email: sjreed@edcomputing.com
  ip: 76.217.157.147
  url: http://www.giskey.com
  date: '2013-05-08 15:30:52'
  body: 'My problem is that I am getting this error while doing a GetInterfaceObject("AutoCAD.AcCmColor.18")
    in my VBA running on my 64-bit Vista machine with AutoCAD Map 3D 2011.


    I don''t find this is the Registry in either the 32 or 64 bit portions of HKCR.


    Any ideas where this should be registered?

    -----'
