comments:
- author: Vasant PADHIYAR
  email: vasantpadhiyar71@yahoo.com
  ip: 121.247.171.90
  url: ''
  date: '2013-04-15 22:38:59'
  body: Where do I find "HostApplicationServices.h" in ObjectARX-2011?
- author: Fenton Webb
  email: ''
  ip: 132.188.64.218
  url: http://profile.typepad.com/6p0168e88ab160970c
  date: '2013-04-16 09:05:02'
  body: 'it''s in the inc folder of the ObjectARX SDK.

    -----'
