comments:
- author: Steve Hill
  email: stevenh0616@gmail.com
  ip: 173.161.87.42
  url: http://beyondcivil3d.blogspot.com
  date: '2013-08-16 05:48:27'
  body: 'Thanks for the post Virupaksha. So then why did Autodesk skip the letter
    ''C'' when rolling out 2014. 2012 was letter ''A'', 2013 was letter ''B'' and
    2014 is letter ''D''.


    I''m sure Autodesk has a  good reason for it, and it''s not because they don''t
    know the alphabet. ;)'
- author: Fenton Webb
  email: ''
  ip: 132.188.64.219
  url: http://profile.typepad.com/6p0168e88ab160970c
  date: '2013-08-20 15:47:34'
  body: 'Hey Steve


    yes, there was a reason for it. C was a prototype version of AutoCAD which was
    released as a preview, but not yet rolled into the main line.'
- author: Steve Hill
  email: stevenh0616@gmail.com
  ip: 173.161.87.42
  url: http://beyondcivil3d.blogspot.com
  date: '2013-09-05 15:19:31'
  body: I see. Thanks Fenton.
- author: Will Baron
  email: ''
  ip: 91.108.160.238
  url: http://profile.typepad.com/6p01a511c76bfd970c
  date: '2014-06-05 03:11:57'
  body: We have found an install on which the French locale ID is not as stated it
    was in fact not 040C, it was 40C. Which is correct, the one above or what we found
    after installing the French version? Does this apply to Spanish, and I guess Hungarian
    too? It is not that we support these languages particularly, just want to be sure
    the documentation is correct for all who use this.
- author: Amar
  email: amar_kanade@yahoo.com
  ip: 73.37.142.98
  url: ''
  date: '2015-03-27 11:47:27'
  body: "Hello,\nI have a drawing file and it takes about 5 minutes to open. Any drawing\
    \ file that is generated from a specific Lenovo machine creates this huge delay\
    \ in opening the file. \n\nIt accesses the Registry a lot. I have attached the\
    \ snapshot of the registry access . This was generated by ProcMon (SysInternals).\
    \ Please let  me know if there is any solution.... \n\nThanks in advance....\n\
    \n1:41:27.2821764 PM\tacad.exe\t4896\tRegOpenKey\tHKLM\\Software\\Autodesk\\AutoCAD\\\
    R20.0\\ACAD-E001:409\tSUCCESS\tDesired Access: Read\n1:41:27.2821933 PM\tacad.exe\t\
    4896\tRegQueryValue\tHKLM\\SOFTWARE\\Autodesk\\AutoCAD\\R20.0\\ACAD-E001:409\\\
    LocaleId\tSUCCESS\tType: REG_SZ, Length: 8, Data: 409\n1:41:27.2822090 PM\tacad.exe\t\
    4896\tRegQueryValue\tHKLM\\SOFTWARE\\Autodesk\\AutoCAD\\R20.0\\ACAD-E001:409\\\
    LocaleId\tSUCCESS\tType: REG_SZ, Length: 8, Data: 409\n1:41:27.2822256 PM\tacad.exe\t\
    4896\tRegCloseKey\tHKLM\\SOFTWARE\\Autodesk\\AutoCAD\\R20.0\\ACAD-E001:409\tSUCCESS"
- author: Andrey Bushman
  email: bushman.andrey@gmail.com
  ip: 87.249.45.171
  url: https://sites.google.com/site/bushmansnetlaboratory/
  date: '2015-04-24 00:43:25'
  body: '>E002 Map

    Is it AutoCAD Map? I am asking because among products also Inventor and DWG TrueView
    was listed also.


    >(Registry Cookie: ACLT-8001)

    Does it mean the Registry Cookies is "ACAD" when it is not pointed in your list?


    >(Registry Cookies: ACAD-D001; ARD-D001)

    Why exist two variants? When am I to expect each of them?'
- author: Andrey Bushman
  email: bushman.andrey@gmail.com
  ip: 87.249.45.171
  url: https://sites.google.com/site/bushmansnetlaboratory/
  date: '2015-04-24 01:23:25'
  body: 'What is Registry Cookie for Inventor and DWG Viewer?


    Also, can you write the same lists for AutoCAD versions older than AutoCAD 2011?
    It is necessary for me for testing. Thank you.'
- author: Andrey Bushman
  email: bushman.andrey@gmail.com
  ip: 87.249.45.171
  url: https://sites.google.com/site/bushmansnetlaboratory/
  date: '2015-04-24 01:24:04'
  body: And for AutoCAD 2016 also. :)
- author: Andrey Bushman
  email: bushman.andrey@gmail.com
  ip: 87.249.45.171
  url: http://bushman-andrey.blogspot.ru/
  date: '2015-04-29 02:06:27'
  body: 'Reader of this article be careful, read this: <a href="http://www.theswamp.org/index.php?topic=49368.new#new">http://www.theswamp.org/index.php?topic=49368.new#new</a>'
- author: Virupaksha Aithal
  email: ''
  ip: 182.73.112.18
  url: http://profile.typepad.com/6p0168e8800efa970c
  date: '2015-04-29 02:44:54'
  body: EO02 is AutoCAD Map. I have removed ARD-D001 from the blog
- author: Virupaksha Aithal
  email: ''
  ip: 182.73.112.18
  url: http://profile.typepad.com/6p0168e8800efa970c
  date: '2015-04-29 02:45:50'
  body: sorry, i do not have information on AutoCAD 2011 and older versions.
- author: Virupaksha Aithal
  email: ''
  ip: 182.73.112.18
  url: http://profile.typepad.com/6p0168e8800efa970c
  date: '2015-04-29 02:53:54'
  body: sorry, now, i have corrected the examples in blog (for AutoCAD 2013 as mentioned
    your swamp blog.)
- author: Andrey Bushman
  email: bushman.andrey@gmail.com
  ip: 87.249.45.171
  url: http://bushman-andrey.blogspot.ru/
  date: '2015-04-29 03:44:09'
  body: Why you deleted all mentions about the Registry Cookies? It had useful info.
- author: Virupaksha Aithal
  email: VIRUPAKSHA.AITHAL@AUTODESK.COM
  ip: 27.56.179.87
  url: ''
  date: '2015-04-29 20:42:58'
  body: 'I am not in position to confirm the Registry Cookies for now. I have Inherited
    this document. I will update the document once i test the Cookies myself. there
    are still lot of Cookies which i am not able to confirm like DwgViewer , Autodesk
    Utility Design, DWG TrueView etc for now. but i have left them in the document.


    Thanks

    Viru'
- author: raghu
  email: raghu_adal@rediffmail.com
  ip: 223.30.231.162
  url: ''
  date: '2015-08-26 02:40:12'
  body: "dear sir when i active autocad .invalid address formatting \nso i requested\
    \ who to file the address line ."
- author: peter
  email: peter.mueller@aresdata.de
  ip: 217.68.171.7
  url: ''
  date: '2015-12-14 06:51:13'
  body: 'What is about the LocaleID''s from French, Spanish and Hungarian Version?

    I will confirm, that the LocaleID from french-Version is not 040C , but "40C".

    Did anyone can check the Spanish an Hungarian Version?'
- author: peter
  email: peter.mueller@aresdata.de
  ip: 217.68.171.7
  url: ''
  date: '2015-12-14 07:51:40'
  body: 'confirmed: Spanish LocaleID is "40A" !'
- author: Herbert
  email: notlongvalid@mnet-online.de
  ip: 31.3.154.85
  url: ''
  date: '2016-06-15 02:51:36'
  body: Is there an update with registrykeys for the 2017-versions?
- author: sandeep
  email: sandeep.kumar@autodesk.com
  ip: 182.73.112.18
  url: ''
  date: '2016-06-16 01:51:29'
  body: 'Hi,


    refer <a href="http://jtbworld.com/autocad-information">http://jtbworld.com/autocad-information</a>'
- author: sandeep
  email: sandeep.kumar@autodesk.com
  ip: 182.73.112.18
  url: ''
  date: '2016-06-16 01:52:23'
  body: "Hi, \n\nrefer <a href=\"http://jtbworld.com/autocad-information\">http://jtbworld.com/autocad-information</a>\
    \ \n\nsandeep\n-----"
