comments:
- author: Taher
  email: taherhamdy_76@yahoo.com
  ip: 78.93.227.188
  url: ''
  date: '2013-12-30 23:02:01'
  body: 'Hi Philippe Leefsma,

    I''m beginner to autocad & .net . I try to make my first program in vb.net2012
    I add reference the two dll file (Acdbmgd.dll, Acmgd.dll) and add the following
    import


    Imports Autodesk.AutoCAD.Runtime

    Imports Autodesk.AutoCAD.ApplicationServices

    Imports Autodesk.AutoCAD.DatabaseServices

    Imports Autodesk.AutoCAD.Geometry


    It give me message.

    (Debugger detected - please close it down and restart!

    Window NT users: Please note that having the WinIce/ SoftIce service installed
    means the you are running a debugger !)



    I hope to find a solution to my problem


    taherhamdy_76@yahoo.com'
- author: Philippe
  email: philippe.leefsma@autodesk.com
  ip: 86.219.228.107
  url: ''
  date: '2013-12-31 01:01:00'
  body: "Hi Taher,\n\nYour question has nothing to do with the topic discussed in\
    \ that post. You can take a look at my first plug-in if you are starting with\
    \ the API: \n\n<a href=\"http://usa.autodesk.com/adsk/servlet/index?id=18162650&siteID=123112\"\
    >http://usa.autodesk.com/adsk/servlet/index?id=18162650&siteID=123112</a>\n\n\
    In the future please post this kind of question on the forum:\n\n<a href=\"http://forums.autodesk.com/t5/AutoCAD-Customization/ct-p/AutoCADTopic1\"\
    >http://forums.autodesk.com/t5/AutoCAD-Customization/ct-p/AutoCADTopic1</a>\n\n\
    Thank you,\nPhilippe."
- author: Stephen Preston
  email: ''
  ip: 108.236.113.147
  url: http://profile.typepad.com/stephenpreston
  date: '2014-01-01 13:14:21'
  body: 'Hi Taher,


    I''ve deleted your numerous comments identical to this. Please refrain from spamming
    the same question on multiple posts.


    As Philippe already mentioned, please post your technical support questions to
    the AutoCAD .NET Discussion Group and someone there will help you.


    Regards,


    Stephen'
- author: Konstantin
  email: konstantinos.sakellaris@uba.uni-heidelberg.de
  ip: 129.206.83.222
  url: ''
  date: '2014-01-09 08:34:00'
  body: 'Hello Philippe,


    Is it possible to have the WCF server hosted by an AutoCAD .Net plug-in on one
    machine and several WCF client executables running on different machines within
    a LAN or WAN ?

    If yes what should be changed in the provided code ?


    Best Regards

    Konstantin'
- author: Philippe Leefsma
  email: ''
  ip: 92.105.24.95
  url: http://profile.typepad.com/6p0167638460d1970b
  date: '2014-01-09 08:43:26'
  body: "Hi Konstantin,\n\nYes it's possible, if you want to use WCF/SOAP then you\
    \ would need (according to the chart) to use netTcpBinding. I wrote an article\
    \ on it already: \n\n<a href=\"http://adndevblog.typepad.com/cloud_and_mobile/2012/08/creating-a-cloud-based-viewerpart-iv.html\"\
    >http://adndevblog.typepad.com/cloud_and_mobile/2012/08/creating-a-cloud-based-viewerpart-iv.html</a>\n\
    \nIf you are not familiar with WCF, you may actually want to check the whole series\
    \ on the same blog: \n\nCreating a cloud based viewer – Part I to X \n\nCheers,\n\
    Philippe."
- author: Konstantin
  email: konstantinos.sakellaris@uba.uni-heidelberg.de
  ip: 129.206.83.100
  url: ''
  date: '2014-01-10 03:57:54'
  body: 'Hello Philippe,


    many thanks, i will go through them...


    Regards

    Konstantin'
- author: Konstantin
  email: KONSTANTINOS.SAKELLARIS@UBA.UNI-HEIDELBERG.DE
  ip: 129.206.83.222
  url: ''
  date: '2014-01-17 03:32:02'
  body: "Hi Phillipe,\ni have been working through the current and your 2 articles\n\
    Creating a cloud based viewer – Part I\nCreating a cloud based viewer – Part II\
    \ \nand everything is setup and running !\nI was able to use WCF Server and Clients\
    \ on different mashines using netTcpBinding.\nFine indeed !\nI would like to replace\
    \ the client application (WCF client) in the current article \nby the Client Viewer\
    \ from  \"Creating a cloud based viewer – Part II\" !\n****************\nI just\
    \ want to test transferring a DWG stream from a DWG open in AutoCAD on the server\
    \ \nor just being on the Server disk using the ACADserver plug-in and display\
    \ it in the Client DWG Viewer.\n****************\nI don't have any clue how to\
    \ transfer and display a DWG Stream in the WCF Client DWG Viewer !\nHow can i\
    \ view DWG in a WCF Client Viewer ?\n\nCould you please describe how to proceed\
    \ or extend the current article showing\nhow to transfer a DWG Stream from the\
    \ WCF ACADserver to a WCF Client DWG Viewer ?\n\nMany thanks in advance .\nBest\
    \ Regards\nKonstantin"
- author: Philippe Leefsma
  email: ''
  ip: 132.188.32.25
  url: http://profile.typepad.com/6p0167638460d1970b
  date: '2014-01-20 05:33:14'
  body: "You can find numerous resources over the internet that illustrates how to\
    \ transfer a stream using WCF. \n\nHere is one for example:\n\n<a href=\"http://www.codeproject.com/Articles/166763/WCF-Streaming-Upload-Download-Files-Over-HTTP\"\
    >http://www.codeproject.com/Articles/166763/WCF-Streaming-Upload-Download-Files-Over-HTTP</a>\n\
    \nTo display a dwg the solutions are pretty limited. You can use either AutoCAD,\
    \ your own viewer based on RealDWG or the AcCtrl control as illustrated below:\n\
    \n<a href=\"http://through-the-interface.typepad.com/through_the_interface/2008/03/embedding-autoc.html\"\
    >http://through-the-interface.typepad.com/through_the_interface/2008/03/embedding-autoc.html</a>"
- author: Konstantin
  email: KONSTANTINOS.SAKELLARIS@UBA.UNI-HEIDELBERG.DE
  ip: 129.206.83.222
  url: ''
  date: '2014-01-22 01:12:19'
  body: 'OK ! Thanks Philippe

    I''ll go through these materials...'
- author: Ben
  email: benkoshy@hotmail.com
  ip: 165.228.230.183
  url: ''
  date: '2016-03-17 16:56:27'
  body: 'Hello Taher,


    perhaps i shouldn''t indulge you here in this particular post. but i was curious:
    are you using genuine software or pirate software?


    regards


    Ben

    -----'
