comments:
- author: Owen Wengerd
  email: owenw@manusoft.com
  ip: 24.140.112.242
  url: http://otb.manusoft.com
  date: '2013-01-15 19:10:45'
  body: Is there some reason why your sample avoids the use of AcCmColor::setRGB()
    or other member functions intended to set color values?
- author: Gopinath Taget
  email: ''
  ip: 67.188.203.224
  url: http://profile.typepad.com/6p0168e89c0a52970c
  date: '2013-01-16 20:42:53'
  body: 'Hi Owen,


    We do show the usage of setRGB in the code above along with the setColor method.


    Cheers

    Gopinath'
- author: Owen Wengerd
  email: owenw@manusoft.com
  ip: 24.140.112.242
  url: http://otb.manusoft.com
  date: '2013-01-16 22:12:04'
  body: I see. I think the call to setRGB() sets the color method to byColor, so the
    prior call to setColorMethod() is not needed.
- author: Veli Väisänen
  email: veli.vaisanen@symetri.com
  ip: 85.29.87.152
  url: ''
  date: '2020-10-14 03:42:23'
  body: 'Just update that AcCmColor::setColorMethod is deprecated on ObjectARX 2021.

    -----'
