comments:
- author: Anthony Conte
  email: ''
  ip: 50.183.30.195
  url: http://profile.typepad.com/6p01b7c8f2b410970b
  date: '2017-04-29 09:10:46'
  body: 'Hello Adam,

    As a follow up to my comment yesterday, I think I have answered my own question.
    The rebuilt assemblies must be the same version. After fixing my assembly version
    in assemblyinfo.cs, the new assemblies load into my updated OEM product.


    Best Regards,

    Anthony'
- author: Anthony Conte
  email: ''
  ip: 50.183.30.195
  url: http://profile.typepad.com/6p01b7c8f2b410970b
  date: '2017-04-29 09:17:09'
  body: 'I don''t see my previous comment, but for anyone interested, my updated assemblies
    were not loading after being updated in my OEM product folder even after replacing
    every file with binary differences in the folder tree. It seems that assembly
    version is still registered somewhere and must remain the same.

    -----'
