comments:
- author: Khoa Ho
  email: ''
  ip: 138.57.212.12
  url: http://profile.typepad.com/6p01a73e0e743b970d
  date: '2014-09-03 07:19:09'
  body: This is a great tool from Cyrille. I tested it works as expected. Thanks.
- author: Super Action Man
  email: kyled.gray@rubicongeological.com
  ip: 76.177.226.11
  url: ''
  date: '2015-12-07 13:05:18'
  body: 'I personally prefer Slide Man. Not free but it is amazing!

    <a href="http://www.graytechnical.com/software/slide-man/">http://www.graytechnical.com/software/slide-man/</a>'
- author: Don
  email: dscribner@maine.rr.com
  ip: 24.103.197.2
  url: ''
  date: '2016-06-02 07:51:58'
  body: The tool locks up and Windows shuts it down. Very disappointing but expected.
- author: MIKE KRAMER
  email: mike@jmkandassociates.com
  ip: 68.3.107.211
  url: ''
  date: '2020-05-26 08:14:41'
  body: 'I CANNOT GET SLM TO INSTALL ON MY COMPUTER I''M USING AUTOCAD 2000 AND WINDOWS
    XP IS THAT A PROBLEM?

    MIKE KRAMER'
- author: Michael Lemick
  email: mikelemick@keeneydesign.com
  ip: 73.34.101.0
  url: ''
  date: '2021-08-10 08:15:46'
  body: 'I tried it with AutoCAD 2013 running under Windows 10. It seems to work fine,
    but when you save a slide library and then call up the image menu using it ALL
    of the slides are blank.

    -----'
