comments:
- author: CAD bloke
  email: ''
  ip: 101.164.209.79
  url: http://profile.typepad.com/cad_bloke
  date: '2015-12-18 01:18:44'
  body: 'This has been discussed a lot at The Swamp. See <a href="http://www.theswamp.org/index.php?topic=50202.0">http://www.theswamp.org/index.php?topic=50202.0</a>
    and have a look at the other threads linked in the first post for a variety of
    approaches.


    I wrote Code Linker (it''s on that Swamp link) because the housekeeping got too
    unwieldy with a lot of build configurations and phantom project references (see
    <a href="http://www.theswamp.org/index.php?topic=49039.msg541744#msg541744)">http://www.theswamp.org/index.php?topic=49039.msg541744#msg541744)</a>
    but I think different approaches will work for different people in different situations.'
- author: Balaji
  email: ''
  ip: 182.73.112.18
  url: http://profile.typepad.com/6p016303198bdc970d
  date: '2015-12-18 02:11:15'
  body: 'Thanks for sharing the Code Linker and that detailed discussion.


    There is a treasure of information in that post.


    Regards,


    Balaji


    -----'
