comments:
- author: gabriel sallum
  email: gsallum@eaglemanufacturinggroup.com
  ip: 12.23.163.67
  url: ''
  date: '2016-06-09 07:12:43'
  body: "Hi, Thanks for the blog. I've have been fighting with this for some time\
    \ now. \nThe problem is that I cannot seem to get this going correctly. \n\nAs\
    \ per your instructions, I seem to fall into the category of having to re-copy\
    \ the Dll back into the ReadDWG dir. My issue is that on the RealDWG dir the \"\
    acdbmgd.dll\" is already one that has 6.3 megs, on the install Distribution, it\
    \ seems that there are a couple of versions but most fall under 2 categories,\
    \ one with small (kb) size and another with a lager ~6mb size. As previously stated,\
    \ I fall in the category of having the larger one in my DWG folder. So I guess\
    \ I need to copy the smaller one (kb sized) into the RealDWG directory ? \n\n\
    thanks, \nIts appreciated\n-----"
