comments:
- author: Kerry Brown
  email: ''
  ip: 122.108.232.189
  url: http://profile.typepad.com/kerrybrown
  date: '2015-11-25 09:40:32'
  body: 'Hi  Balaji,


    Can you please explain why you use the <i>default</i> keyword when you declare
    the variables ?


    Thanks,

    Regards,'
- author: Balaji
  email: ''
  ip: 182.73.112.18
  url: http://profile.typepad.com/6p016303198bdc970d
  date: '2015-11-25 22:32:12'
  body: 'Hi Kerry,


    I had implemented the code in this blog post initially in VB.Net and later used
    an online converter to do the C# conversion for the sake of creating this blog
    post. The converter had introduced this and i did not notice it. Sorry, I do not
    know what that means. But, the C# version did build and run ok in AutoCAD.


    Please do let me know if you have any information on it.


    This is the converter that i had used for my VB.Net to C# conversion :

    converter.telerik.com


    Thanks


    Balaji'
- author: Kerry Brown
  email: ''
  ip: 122.108.232.189
  url: http://profile.typepad.com/kerrybrown
  date: '2015-11-25 23:28:55'
  body: "I didn't think it was needed initially, then it started to interest me because\
    \ I decided this may be something new I needed to know.\nI posted on the Swamp\
    \ <a href=\"http://www.theswamp.org/index.php?topic=50511.msg556363#msg556363.\"\
    >http://www.theswamp.org/index.php?topic=50511.msg556363#msg556363.</a> \nThe\
    \ consensus was that it was not necessary.\n\nThanks for your response.\nAnd thank\
    \ you particularly for your contributions to the learning pool.\n\nRegards,"
- author: Андрей Бушман
  email: ''
  ip: 87.249.45.171
  url: http://profile.typepad.com/d107779829232736013
  date: '2015-11-26 02:04:34'
  body: 'The working with each option of MLeaderStyle maybe is interesting too for
    some developers: <a href="http://bushman-andrey.blogspot.ru/2014/06/autocad_8823.html">http://bushman-andrey.blogspot.ru/2014/06/autocad_8823.html</a>'
- author: Balaji
  email: ''
  ip: 182.73.112.18
  url: http://profile.typepad.com/6p016303198bdc970d
  date: '2015-11-26 22:12:06'
  body: 'Hi Андрей,


    Thanks for sharing this nice blog post.


    Regards,

    Balaji'
- author: backrooms game
  email: floydprice149@gmail.com
  ip: 58.186.68.240
  url: https://backroomsgame.io
  date: '2022-09-18 20:07:25'
  body: I appreciate you sharing this good article piece.
- author: io games
  email: jimbrett0712@gmail.com
  ip: 212.102.46.66
  url: https://iogames.games
  date: '2023-09-27 01:56:14'
  body: 'The best blog ever is your post. Your post is interesting and interesting


    -----'
