comments:
- author: Jamie
  email: jaa865@ftr.com
  ip: 50.121.72.30
  url: ''
  date: '2017-02-02 08:31:02'
  body: "Where do I find additional information about the usage of this new class?\
    \ \n\nThere are lots of methods I would like to use but the arx documentation\
    \ (arxref.chm) is pretty much useless for this. \n\nFor instance the bool Initialize();\
    \ method will lock up AutoCAD."
- author: Tom DiVittis
  email: tdivittis@keystoneconsultants.net
  ip: 50.197.33.85
  url: ''
  date: '2017-02-27 12:52:40'
  body: 'I''ll second the request.  ;)

    -----'
