comments:
- author: Alexander Rivilis
  email: ''
  ip: 81.95.185.60
  url: http://profile.typepad.com/rivilis1964
  date: '2016-02-13 11:53:02'
  body: 'Hi Adam!

    As far as I remember AutoCAD read changed registry variables only after it restart
    (next session) unlike of getenv/setenv. So it is not ideal solution.'
- author: Alexander Rivilis
  email: ''
  ip: 81.95.185.60
  url: http://profile.typepad.com/rivilis1964
  date: '2016-02-13 12:10:50'
  body: 'P.S.: I''ve tested this code and find that AutoCAD check <b>this</b> variable
    from registry every time. So for this variable it is a quite well solution. Thanks!

    -----'
