comments:
- author: Dan
  email: daniel@cadext.com
  ip: 116.86.21.134
  url: https://github.com/CEXT-Dan/PyRx
  date: '2023-11-12 04:36:28'
  body: "It’s really handy. I’ve been embedding SQLite in my ARX apps for years. great\
    \ for storing settings, \nbut you can also store files i.e .dwg blocks or, block\
    \ Icons \n\none such module is  SQLite for AutoLisp\n<a href=\"https://www.theswamp.org/index.php?topic=28286.0\"\
    >https://www.theswamp.org/index.php?topic=28286.0</a>"
- author: dino game
  email: jacefas266@hupoi.com
  ip: 14.191.165.218
  url: https://dinogame.one
  date: '2023-12-12 20:25:07'
  body: Dino Game is a speed game that was first made for Google Chrome. The game
    was added to Google Chrome in 2014 as a "Easter egg" to keep people busy when
    they can't get online. Every month, more than 270 million people play a game called
    "Chrome Dino" that has a T-Rex in it. The Dinosaur Game can be played in full
    screen, even when you are online.
- author: Annata Evan
  email: annata0215@gmail.com
  ip: 42.113.75.105
  url: ''
  date: '2024-01-30 01:21:19'
  body: Integrating an ARX (Augmented Reality) application with SQLite involves using
    SQLite as the database management system for storing and retrieving data related
    to your AR experience.
- author: Pokerogue
  email: aliacacia521@gmail.com
  ip: 42.118.22.5
  url: https://pokerogue.org/
  date: '2024-06-03 17:46:21'
  body: 'In the realm of digital gaming, innovation is the key to capturing the attention
    of avid players. Enter Pokerogue, a groundbreaking game that masterfully blends
    the strategic depth of poker with the thrilling unpredictability of a roguelike
    adventure.

    -----'
