comments:
- author: Albert
  email: szilvaa@hotmail.com
  ip: 198.102.112.18
  url: ''
  date: '2006-11-02 17:54:29'
  body: 'You can use the probing element to specify a sub directory under the main
    exe folder for the framework to search. Note that you can not specify an arbitrary
    directory only ones under the exe dir. If you use you registered dev symbol to
    prefix the folder then you should be able to avoid conflicts with other apps.


    Albert'
- author: Albert
  email: szilvaa@hotmail.com
  ip: 198.102.112.18
  url: ''
  date: '2006-11-02 17:54:30'
  body: 'You can use the probing element to specify a sub directory under the main
    exe folder for the framework to search. Note that you can not specify an arbitrary
    directory only ones under the exe dir. If you use you registered dev symbol to
    prefix the folder then you should be able to avoid conflicts with other apps.


    Albert'
- author: Kean
  email: kean.walmsley@autodesk.com
  ip: 132.188.32.100
  url: ''
  date: '2006-11-03 09:31:22'
  body: 'Thanks, Albert.


    The concern I had was more around people replacing the singleton "probing" element
    with their own. As long as the new directories get appended to the "privatePath"
    attribute, rather than the element being replaced, then that concern is eliminated.


    Kean'
- author: Rayban
  email: raybandxb@hotmail.com
  ip: 220.146.149.221
  url: ''
  date: '2007-04-22 05:28:42'
  body: 'I can''t open AutoCAD 2006 a message appears:


    "acad.exe - entry point not found"


    The procedure entry point adsw_acadMainWnd could not be located in the dynamic
    library ACAD.EXE.


    I look everywhere on the net but I couln''t find an answer. Can you please help
    me.

    Thank you very much.'
- author: Kean
  email: kean.walmsley@autodesk.com
  ip: 132.188.32.100
  url: http://blogs.autodesk.com/through-the-interface
  date: '2007-04-22 13:39:06'
  body: Sorry, I don't know why this is happening. Please post your question - with
    as much supporting information as possible regarding the circumstances of the
    error - to the relevant discussion group on http://discussion.autodesk.com.
- author: Glenn
  email: oano@mac.com
  ip: 75.109.218.88
  url: ''
  date: '2007-08-28 20:50:28'
  body: 'I don''t see that the line <supportedRuntime version="v1.1.4322"/> is commented
    out.  Actually, it appears that it is uncommented, as commenting is ( <!â€”this
    is a comment --> )


    Am I wrong on this?  Please explain how to uncomment this line.'
- author: Kean
  email: kean.walmsley@autodesk.com
  ip: 132.188.32.100
  url: http://blogs.autodesk.com/through-the-interface
  date: '2007-08-28 22:45:41'
  body: 'Commenting is <!-- comment --> in XML, as far as I recall.


    Kean

    -----'
