comments:
- author: Rod Howarth
  email: rodhowarth257@gmail.com
  ip: 124.171.161.41
  url: http://roddotnet.blogspot.com
  date: '2009-05-31 10:18:27'
  body: Excellent! I've started using WPF for my revit add-ins and I'm loving it!
- author: Drew Avis
  email: drew.avis@autodesk.com
  ip: 69.165.156.64
  url: ''
  date: '2009-06-03 19:45:19'
  body: 'Thanks for the reminder, Kean, I signed up for #1 and it was well worth it.  Any
    chance you could link to the code samples here?

    -----'
