comments:
- author: ben
  email: bodxp@163.com
  ip: 203.86.47.59
  url: ''
  date: '2009-02-12 06:04:59'
  body: good,really make me excited!
- author: markc
  email: mark.carson@fairhurst.co.uk
  ip: 194.75.137.130
  url: ''
  date: '2009-02-23 09:37:17'
  body: 'Does this mean that to develop in AutoCAD 2010 we require an upgrade to Visual
    Studio 2008 SP1?


    .NET Framework 3.0? 3.5?'
- author: Kean Walmsley
  email: ''
  ip: 88.85.22.207
  url: http://profile.typepad.com/walmsleyk
  date: '2009-02-23 09:39:41'
  body: 'Not at all - you can continue to work with previous versions of Visual Studio
    (and the .NET Framework), although certain functionality requiring newer versions
    of the framework will not be available to you. At least that''s my understanding.


    Kean'
- author: markc
  email: mark.carson@fairhurst.co.uk
  ip: 194.75.137.130
  url: ''
  date: '2009-02-23 09:42:39'
  body: Very prompt reply. Thanks.
- author: markc
  email: mark.carson@fairhurst.co.uk
  ip: 92.235.21.8
  url: ''
  date: '2009-03-22 15:14:34'
  body: 'Another question. Having just downloaded AutoCAD 2010 from Product Downloads
    on subscription, where is the ObjectARX 2010. Do we have to wait for this?


    I referenced a few dlls in the application directly and was blown away by the
    additional features. It would help to get some pointers...'
- author: Kean Walmsley
  email: ''
  ip: 88.85.22.207
  url: http://profile.typepad.com/kean
  date: '2009-03-22 19:41:14'
  body: 'ObjectARX 2010 is available now for Autodesk Developer Network members (from
    <a href="http://adn.autodesk.com">the ADN site</a>), and should be available sometime
    this week from <a href="http://www.autodesk.com/objectarx">the public ObjectARX
    download site</a>.


    Kean'
- author: Stardust1611
  email: ''
  ip: 92.36.241.143
  url: http://profile.typepad.com/6p01156f3a6f3b970c
  date: '2009-04-20 21:49:28'
  body: 'I have created an application in Visual Studio 2008 (it''s not SP1) with
    C# and it worked perfectly with AutoCAD 2009. But, now, with 2010 I get this error:


    Application does not support just-in-time (JIT)

    debugging. See the end of this message for details.


    ************** Exception Text **************

    System.Exception: The component ''Autodesk.AutoCAD.AcInfoCenterConn.MyAutoCADBalloon''
    does not have a resource identified by the URI ''/AcWindows;component/infocenteracconn/myautocadballoon.xaml''.


    ************** JIT Debugging **************

    Application does not support Windows Forms just-in-time (JIT)

    debugging. Contact the application author for more

    information.


    I referenced all necessary files in autocad 2010, and I don''t understand what''s
    the problem?'
- author: Kean Walmsley
  email: ''
  ip: 88.85.22.207
  url: http://profile.typepad.com/kean
  date: '2009-04-20 21:55:57'
  body: 'Sorry - no idea...


    You might try submitting a sample project that reproduces the problem <a href="http://adn.autodesk.com">via
    ADN</a>, if you''re a member, or otherwise someone on <a href="http://discussion.autodesk.com/forums/forum.jspa?forumID=152">the
    AutoCAD .NET Discussion Group</a> might be able to help.


    Regards,


    Kean'
- author: Stardust1611
  email: ''
  ip: 92.36.249.4
  url: http://profile.typepad.com/6p01156f3a6f3b970c
  date: '2009-04-21 12:04:10'
  body: Thanks Kean for the reply. I'm not a member of ADN. I was wandering are the
    two assemblies AcInfoCenterConn.dll and AdInfoCenter.dll missing in AutoCAD 2010,
    or were they perhaps named differently? They contain the IExtensionApplication
    interface, which contains the methods Initialize() and Terminate() that you were
    explaining in one of the articles. It seems that this is the reason why I'm getting
    the error mentioned above. Thanks.
- author: Kean Walmsley
  email: ''
  ip: 88.85.22.207
  url: http://profile.typepad.com/kean
  date: '2009-04-21 13:01:33'
  body: "Erm... you don't need either of these components to use Initialize()/Terminate().\
    \ \n\nAre you actually using them for anything?\n\nKean"
- author: Stardust1611
  email: ''
  ip: 92.36.249.4
  url: http://profile.typepad.com/6p01156f3a6f3b970c
  date: '2009-04-21 13:09:36'
  body: 'No. I do use Initialite() to load my customization .cuix file. I posted the
    problem yesterday on the forum if you care to take a look: http://discussion.autodesk.com/forums/thread.jspa?messageID=6166543&

    It''s described more thoroughly.'
- author: Stardust1611
  email: ''
  ip: 92.36.241.71
  url: http://profile.typepad.com/6p01156f3a6f3b970c
  date: '2009-05-02 17:17:30'
  body: I discovered what was causing this problem. I noticed I didn't set Copy Local
    to false on some of my references, and when I did that, the error disappeared.
    Thanks anyways.
- author: Stacy
  email: stacy@hummel-associates.com
  ip: 141.152.29.125
  url: ''
  date: '2010-01-28 22:07:25'
  body: Can 2009 read a 2010 autodesk drawings aec objects?
- author: Kean Walmsley
  email: ''
  ip: 88.85.0.178
  url: http://profile.typepad.com/kean
  date: '2010-01-28 23:26:05'
  body: 'I''m afraid I don''t know (but suspect not). You might try posting to the
    appropriate <a href="http://discussion.autodesk.com">online discussion group</a>.


    Kean'
- author: 'Nithesh '
  email: nvrde@rediffmail.com
  ip: 124.124.54.130
  url: ''
  date: '2010-09-14 12:05:30'
  body: "Hi kean\n Iam entirely new to This functional area.Can yu tell me how to\
    \ determine which of th lines form a polygon .[given five set of lines]"
- author: Kean Walmsley
  email: ''
  ip: 132.188.32.100
  url: http://profile.typepad.com/kean
  date: '2010-09-14 12:07:45'
  body: 'This isn''t a forum for support.


    Your comment doesn''t appear to relate to this post, so please submit your question
    to <a href="http://adn.autodesk.com">the ADN team</a>, if you''re a member, or
    otherwise <a href="http://discussion.autodesk.com/forums/forum.jspa?forumID=152">the
    AutoCAD .NET Discussion Group</a>.


    Kean'
- author: Nithesh
  email: nvrde@rediffmail.com
  ip: 124.124.54.130
  url: ''
  date: '2010-09-14 12:56:27'
  body: 'I am clear in logic but I cannot able to implement it.Reply me with the code.

    Thans in advance'
- author: Kean Walmsley
  email: ''
  ip: 132.188.32.100
  url: http://profile.typepad.com/kean
  date: '2010-09-14 13:23:49'
  body: 'Please see my other replies. This blog is not a way to get support.


    If you continue to post such comments, I''ll have no choice but to delete them
    from the site.


    Kean'
- author: Rama Krishna
  email: ''
  ip: 213.181.44.4
  url: http://profile.typepad.com/krishnarama1
  date: '2011-08-25 16:39:00'
  body: After overriding the subworlddraw, it is not getting triggerd??
- author: Kean Walmsley
  email: ''
  ip: 80.83.34.178
  url: http://profile.typepad.com/kean
  date: '2011-08-25 17:09:52'
  body: 'Sorry - I have no idea. Please post your code via ADN or to the AutoCAD .NET
    Discussion Group.


    Kean'
- author: webfiaz@live.com
  email: fia.fiyasahammed@gmail.com
  ip: 86.96.226.19
  url: ''
  date: '2011-10-10 08:03:43'
  body: "hi, \n\ni want open auto cad 2010 file in may auto cad 2008, how it is possible?\
    \ please help me.\n\nXadi."
- author: Kean Walmsley
  email: ''
  ip: 83.68.200.19
  url: http://profile.typepad.com/kean
  date: '2011-10-17 12:33:30'
  body: 'Someone with AutoCAD 2010 or higher will need to save it back to AutoCAD
    2007 (or previous) DWG.


    Please post any further such questions to our discussion group (this is not a
    support forum).


    Kean

    -----'
