comments:
- author: csharpbird
  email: csharpbird@gmail.com
  ip: 221.137.230.169
  url: ''
  date: '2010-03-10 01:40:47'
  body: 'Hi,Kean

    It seems that we cannot write AutoCAD programs with Visual Studio 2010?'
- author: Kean Walmsley
  email: ''
  ip: 132.188.32.100
  url: http://profile.typepad.com/kean
  date: '2010-03-10 08:54:17'
  body: 'Hi 才鸟,


    That''s not my understanding. While I haven''t actually done this, myself, I''m
    sure it can be done (the architect of our .NET interface has been testing with
    VS 2010 from the beginning).


    Regards,


    Kean'
- author: Daniel
  email: daniel@cadext.com
  ip: 222.65.247.67
  url: ''
  date: '2010-03-12 03:15:49'
  body: It seems AutoCAD is not compatible with .NET 4.0 (My tests with the latest
    RC), While you can use VS2010, you will need to target the older CLR. I hope this
    changes with the RTM
- author: Kean Walmsley
  email: ''
  ip: 88.85.16.194
  url: http://profile.typepad.com/kean
  date: '2010-03-12 08:57:37'
  body: 'Great point - had forgotten about that aspect of it.


    Albert presented <a href="http://au.autodesk.com/?nd=class&session_id=5164">a
    session on .NET 4.0 at AU 2009</a>, which includes information on getting AutoCAD
    to use that version of the framework (and the fact there''s an incompatibility).
    See Albert''s presentation for details.


    Kean'
- author: Hugh Compton
  email: info@herculedesign.com
  ip: 83.104.230.248
  url: http://http:%5C%5Cwww.herculedesign.com
  date: '2010-04-26 10:51:05'
  body: 'Kean


    Probably me doing something wrong, but the demand loading (vb.net) code worked
    great on ACA 2010 but doesn''t seem to work on ACA 2011.  No error messages  just
    doesn''t seem to do anything :(


    Has anyone else got this working on 2011?'
- author: Kean Walmsley
  email: ''
  ip: 88.85.16.194
  url: http://profile.typepad.com/kean
  date: '2010-04-26 10:59:05'
  body: 'Hugh,


    I haven''t tried it in ACA 2011, but in AutoCAD 2011 it appears to work fine.


    Could you download and NETLOAD the Clipboard Manager from Labs (in <a href="http://labs.autodesk.com/utilities/ADN_plugins/catalog">the
    plugin catalog</a>) and see if that creates Registry entries on your system?


    Cheers,


    Kean'
- author: Sebas
  email: fake@imsorry.com
  ip: 200.117.139.177
  url: ''
  date: '2010-11-18 15:30:03'
  body: Thanks!! Just what I was looking for. I'm using VS 2010, but FW 3.5, and works
    fine.
- author: Sebas
  email: fake@imsorry.com
  ip: 200.117.139.177
  url: ''
  date: '2010-11-18 15:30:53'
  body: 'Thanks!! Just what I was looking for. I''m using VS 2010, but FW 3.5, and
    works fine.

    -----'
