comments:
- author: J. Daniel Smith
  email: typepad.com@jdanielsmith.org
  ip: 132.188.71.7
  url: ''
  date: '2011-03-11 17:14:57'
  body: My understanding about the "root cause" of this problem/feature is that--unlike
    CRTs--LCDs look best at their "native resolution".
- author: Kean Walmsley
  email: ''
  ip: 132.188.32.100
  url: http://profile.typepad.com/kean
  date: '2011-03-11 17:27:01'
  body: 'Indeed - thanks for mentioning that, Dan.


    Kean'
- author: Mike Caruso
  email: mcaruso@whitemountaincad.com
  ip: 148.183.241.21
  url: http://www.whitemountaincad.com
  date: '2012-04-28 16:05:55'
  body: "In addition, it seems as though AutoCAD does some setting of fonts through\
    \ the palette set. Even when using 96dpi font size, my fonts were larger on the\
    \ palette than in my design view in VS.\n\nThe fonts for all controls need their\
    \ fonts set manually, so they do not inherit the size the palette wants to use:\n\
    \nFor Each ctrl As Control In myctrl1.Controls\n                    ctrl.Font\
    \ = New System.Drawing.Font(\"Microsoft Sans Serif\", 8.25)\n                Next"
- author: Kamyar
  email: Kgh5@raymak.com
  ip: 96.252.107.221
  url: ''
  date: '2013-08-02 02:59:59'
  body: 'I was having a related issue with dot net forms on a windows 7 machine which
    had default DPI of 125%. In particular datagridviews inside of TabStrips were
    not sizing correctly to fill the TabStrips page. I tried switching the AutoScaleMode
    property of the form to <b>Dpi</b>, and it did not help. Surprisingly what fixed
    the issue was switching the AutoScaleMode to <b>None</b>. (The default AutoScaleMode
    was <b>Font</b>).

    -----'
