comments:
- author: James M
  email: jmaeding@hunsaker.com
  ip: 24.249.247.46
  url: ''
  date: '2011-09-06 18:13:15'
  body: Thx for this post Kean, I may not put up any apps for a while, but knowing
    what it takes establishes the amount of effort involved.  It seems to me that
    whole iudea of an app store is to slick out the user experience.  Hopefully there
    will be some kind of submission tool that asks step by step questions that would
    walk through all the steps.  Kind of like slicking it out for the developer too.  If
    I just had a .net dll with one command, i should be able to pick it, fill out
    some info, pick a logo, and have it do the submission, something simple like that.
- author: Kean Walmsley
  email: ''
  ip: 80.83.58.92
  url: http://profile.typepad.com/kean
  date: '2011-09-06 19:21:52'
  body: 'It''ll get easier, as we do more automation on our side (we''re already doing
    a lot, and it''s increasing).


    If you actually look at the work involved (rather than the length of the post),
    there really isn''t that much to it. A little XML editing and some basic CUI work,
    but nothing earth-shattering (but I do see that these steps could be simplified,
    over time).


    And you''ll always have to edit your images, of course. :-)


    Kean'
- author: Mona Akkoush
  email: Mona.Akkoush@dargroup.com
  ip: 95.170.193.82
  url: ''
  date: '2012-02-11 12:02:57'
  body: 'Hello,


    Thanks a lot for this post..


    I am trying to add a test .NET dll to the AutoCAD 2012 Plugins ribbon, but unfortunately
    am not able to see my tool in the Plugins ribbon although am following the same
    steps as you mentioned in this post. The only step am skipping is "Step 6 â€“ update
    the CUIX file". Well, am not sure how can I apply this step & whether it is needed!


    Please advise.


    Thanks in advance,'
- author: Kean Walmsley
  email: ''
  ip: 83.68.200.62
  url: http://profile.typepad.com/kean
  date: '2012-02-13 14:39:06'
  body: 'Updating the CUIX file is exactly how you get your app to display an item
    in the Plug-ins ribbon tab.


    Please try that step, too, and then - if it still doesn''t work - post your problem
    to the AutoCAD .NET Discussion Group or to the ADN team (if you''re a member).


    Kean'
- author: Mona Akkoush
  email: Mona.Akkoush@dargroup.com
  ip: 95.170.193.82
  url: ''
  date: '2012-02-14 12:02:51'
  body: 'Thanks Kean for your reply,

    Unfortunately, I am still facing a problem in executing the command, anyways I
    submitted the problem to ADN team.


    Regards,

    Mona'
- author: MexicanCustard
  email: mexicancustard@gmail.com
  ip: 209.156.249.65
  url: http://www.theswamp.com
  date: '2012-03-02 16:28:55'
  body: 'Kean, do you know if its possible to get AutoCAD to look outside the bundle
    folder to find an Assembly?


    I have DLLs on a network drive and when I try to load them with the autoloader
    the error message shows AutoCAD combining the path I gave with the bundle folder
    path. Which of course leads to AutoCAD not locating the assemby in that location.'
- author: Kean Walmsley
  email: ''
  ip: 72.52.96.11
  url: http://profile.typepad.com/kean
  date: '2012-03-02 23:47:51'
  body: 'I don''t believe full paths are supported (and network drives come with their
    own problems when it comes to .NET security).


    Kean'
- author: kolio
  email: kolio@meta.ua
  ip: 193.110.115.68
  url: ''
  date: '2013-08-02 10:25:24'
  body: 'hi

    i have need to write plugin on delphi

    have you example simple plugin on pascal or .net? i try rewrite into delphi

    wery thanks from ukraine'
- author: Kean Walmsley
  email: ''
  ip: 178.197.236.221
  url: http://profile.typepad.com/kean
  date: '2013-08-02 10:33:38'
  body: 'Sorry - I have no experience with that. Please post your question to the
    relevant (probably .NET) AutoCAD discussion group.


    Kean

    -----'
