comments:
- author: AlexFielder
  email: ''
  ip: 62.22.46.203
  url: http://profile.typepad.com/alexfielder
  date: '2011-01-12 13:28:44'
  body: "Another potentially useful post Kean, thanks.\n\nOn the topic of the Kinect;\
    \ <a href=\"http://bit.ly/eg8gPM\">this</a> looks like it would tie in well with\
    \ the Photofly service; perhaps as a basis for higher resolution images to be\
    \ overlaid on top of the captured scene? \n\nOr maybe the underlying mesh could\
    \ be used negating the need for any other images?"
- author: Kean Walmsley
  email: ''
  ip: 80.83.60.121
  url: http://profile.typepad.com/kean
  date: '2011-01-12 14:09:18'
  body: 'There''s definite potential to use Kinect-like depth cameras along with standard
    camera pixels to map physical objects. <a href="http://www.cs.washington.edu/ai/Mobile_Robotics/projects/rgbd-3d-mapping/">This</a>
    shows it, too.


    We''ll see what happens, over time. The resolution will have to increase to get
    better accuracy, but that kind of increase seems inevitable.


    And thanks, Alex - both for at least one of the links in this post (I forgot to
    credit you for passing it on) and for the Shorty nomination. You''re really too
    kind.


    Kean'
- author: Dave Wolfe
  email: dave.wolfe@ecadinc.com
  ip: 97.81.199.161
  url: ''
  date: '2011-01-12 14:17:51'
  body: Maybe our kids will be able to design the world around them hands on in 3D.  This
    link shows someone who hacked kinect to work with the wii and Call of Duty. It
    gets your imagination going! I wonder if it will be called manual labor at that
    point.  <a href="http://www.pcworld.com/article/216526/kinect_wii_used_to_play_call_of_duty_in_epic_gadget_mashup_hack.html">http://www.pcworld.com/article/216526/kinect_wii_used_to_play_call_of_duty_in_epic_gadget_mashup_hack.html</a>
- author: Gaston Nunez
  email: gaston.nunez@asyst.cl
  ip: 190.22.208.8
  url: http://www.asyst.cl
  date: '2011-01-12 19:29:29'
  body: 'Hi Kean,


    Nice worst case binary search :)'
- author: Kean Walmsley
  email: ''
  ip: 80.83.60.121
  url: http://profile.typepad.com/kean
  date: '2011-01-12 19:57:22'
  body: 'Really! :-)


    Kean

    -----'
