comments:
- author: Felipe Mesquita
  email: felipe@vendramini.eng.br
  ip: 186.220.152.41
  url: http://estrutural.blog.br/
  date: '2011-09-08 19:46:24'
  body: 'Great post Kean! (as usual...)


    Is there any kind of control to avoid the user that bought an App to copy de bundle
    to another machine?


    Any kind of verification (like AppleStore), that checks if the user has bought
    it?


    Thanks!

    Felipe

    SP/Brazil'
- author: Kean Walmsley
  email: ''
  ip: 80.83.58.92
  url: http://profile.typepad.com/kean
  date: '2011-09-08 19:53:22'
  body: 'Thanks, Felipe. :-)


    Great question...


    No - there isn''t any licensing built directly into the Store: it''s up to individual
    developers to manage that.


    I''d encourage erring on the side of flexibility (rather than excessive control),
    e.g. giving customers a straightforward way to license an entire site.


    That said, a lot depends on the size of your IP investment, etc.


    Regards,


    Kean'
- author: Roland
  email: roland@thening.at
  ip: 188.22.9.239
  url: ''
  date: '2011-09-12 15:42:24'
  body: 'Hi!

    Is the ''APP''-Thing disabled in the german Architecture version. Or is there
    anything to activate? I can''t find it.

    Thanks,

    Roland'
- author: Kean Walmsley
  email: ''
  ip: 80.83.58.92
  url: http://profile.typepad.com/kean
  date: '2011-09-12 15:45:25'
  body: 'Hi Roland,


    Good question.


    The Apps tab in Exchange is currently English-only and "vanilla" AutoCAD-only,
    so you''re unfortunately out of luck on a couple of fronts (for now, at least).


    Regards,


    Kean'
- author: Rusel
  email: ruselgun@yahoo.com
  ip: 78.162.214.195
  url: ''
  date: '2013-08-07 01:39:12'
  body: 'Dear Kean,

    How can we find that Autodesk Plug-in installer.

    Regards,'
- author: Kean Walmsley
  email: ''
  ip: 83.68.204.241
  url: http://profile.typepad.com/kean
  date: '2013-08-07 10:46:59'
  body: 'Dear Rusel,


    Sorry - I don''t understand the question.


    Regards,


    Kean'
- author: Melih
  email: melihkagan@gmail.com
  ip: 85.108.150.213
  url: http://www.macrobook.net
  date: '2013-10-29 21:12:43'
  body: "Hi Kean,\n\nFirst of all, thank you for a great site.\n\nIn order to restrict\
    \ the bundle to copy and use on another PC, could we following do?\n\nWith a third\
    \ party licensing software like eziriz (can be found at www.eziriz.com) to prepare\
    \ a limited version? \nAfter the trial period the user can asked for a valid license\
    \ to buy.\nThese licensing software generate unique licenses for every computer\
    \ seperately.\n\nDoes AutoCAD Exchange admit those kind of dll's (trialled) in\
    \ a bundle?\n\nThank You.."
- author: Melih
  email: melihkagan@gmail.com
  ip: 85.108.150.213
  url: http://www.macrobook.net
  date: '2013-10-29 21:38:33'
  body: "Hi Kean,\n\nFirst of all, thank you for the great site.\n\nIn order to restrict\
    \ the bundle to copy and use on another PC, could we following do?\n\nWith a third\
    \ party licensing software like eziriz (can be found at www.eziriz.com) to prepare\
    \ a limited version? \nAfter the trial period the user can asked for a valid license\
    \ to buy.\nThese licensing software generates unique license for every computer.\n\
    \nDoes AutoCAD exchange admit those kind of dll's (trialled) in a bundle?\n\n\
    Thank You.."
- author: Kean Walmsley
  email: ''
  ip: 83.68.204.241
  url: http://profile.typepad.com/kean
  date: '2013-11-13 14:56:18'
  body: 'Hi Melih,


    Sorry - this got flagged as spam and so I didn''t see it until now.


    You can absolutely implement some kind of rights management - we don''t really
    help in that respect, though (we don''t provide access to the technology that
    we use, neither do we recommend a particular provider, as far as I''m aware).


    Regards,


    Kean'
- author: Kean Walmsley
  email: ''
  ip: 83.68.204.241
  url: http://profile.typepad.com/kean
  date: '2013-11-13 14:58:48'
  body: 'I see you repeated your question when it didn''t come up (and this one also
    got flagged as spam).


    Please see my answer above.


    Kean

    -----'
