comments:
- author: Lee Ambrosius
  email: ''
  ip: 75.87.214.201
  url: http://profile.typepad.com/hyperpics
  date: '2012-11-16 14:20:46'
  body: 'Are you going to talk about persisting data between sessions or even across
    different workstations that you log into? I have found one limitation though when
    it comes to apps, and that they are tied to a user''s account only and not sharable/usable
    by all users on that machine.


    I started in my free time a few weeks ago to create a calculator app, not extremely
    exciting but has allowed me to play with persisting data and snapped states.'
- author: Kean Walmsley
  email: ''
  ip: 83.68.204.241
  url: http://profile.typepad.com/kean
  date: '2012-11-16 15:26:07'
  body: 'Hi Lee,


    Sort of. I show a standard desktop app writing data that gets picked up inside
    WinRT, as well as some cloud-hosted application settings that will roam with a
    specific user.


    Both relate to a specific user: I haven''t show how to write and access per-machine
    data in this particular sample.


    Cheers,


    Kean'
- author: Lee Ambrosius
  email: ''
  ip: 75.87.214.201
  url: http://profile.typepad.com/hyperpics
  date: '2012-11-16 15:32:09'
  body: Very nice article from what I read this morning so far though.  Have you had
    a chance to test on a Windows RT device yet?
- author: Kean Walmsley
  email: ''
  ip: 83.68.204.241
  url: http://profile.typepad.com/kean
  date: '2012-11-16 15:33:35'
  body: 'Not a pure WinRT device. I did test on one of the Intel tablets they gave
    out at last year''s Build, but nothing ARM-based.


    Kean'
- author: Lee Ambrosius
  email: ''
  ip: 75.87.214.201
  url: http://profile.typepad.com/hyperpics
  date: '2012-11-16 17:33:55'
  body: Testing on a WinRT tablet is fairly straightforward once you have the device
    configured for remote debugging.  When running the VS debugger, the app is pushed
    to the tablet were you interact with it while the debugger is running from Visual
    Studio 2012 for Windows 8.
- author: Khoa Ho
  email: ''
  ip: 72.37.249.84
  url: http://profile.typepad.com/khoaho
  date: '2012-11-16 18:24:23'
  body: 'Hi Kean, from last paragraphs of your article, it can say: "A new WinRT AutoCAD
    would be a window into a cloud service, where drawings are stored and manipulated
    away from the PC. You''d chose actions, see results, but the actual drawing processing
    would happen on cloud-scale systems."


    RealDWG will never be made available for WinRT, but it can be ported to pure .NET
    desktop to run as a web service on the cloud. It''s interesting that AutoCAD future
    will be cloud-scale services.


    Khoa'
- author: Kean Walmsley
  email: ''
  ip: 178.197.234.45
  url: http://profile.typepad.com/kean
  date: '2012-11-16 20:28:03'
  body: 'Cool - sounds comparable with debugging on a physical Android device with
    Eclipse and on an iOS device with Xcode...


    Kean'
- author: Kean Walmsley
  email: ''
  ip: 178.197.234.45
  url: http://profile.typepad.com/kean
  date: '2012-11-16 20:35:53'
  body: 'Hi Khoa,


    The beauty of a web-service is that you can abstract pretty much anything away
    behind a RESTful protocol (especially if you''re using IaaS). We wouldn''t even
    need to port RealDWG for that.


    For instance, we currently have it running in the cloud to import drawings into
    AutoCAD WS (which is close to what you''ve described in your comment, although
    there is local processing happening in the browser/on the device).


    Admittedly it''s running on AWS, rather than Azure, but the same could be done
    today using Azure, too.


    Regards,


    Kean'
- author: Khoa Ho
  email: ''
  ip: 72.37.249.84
  url: http://profile.typepad.com/khoaho
  date: '2012-11-17 01:54:03'
  body: 'Thanks for the reply. I just played around with AutoCAD WS API and saw it
    does not expose many functionalities. It just mainly opens DWG files saved from
    the WebDav on the Flash-based client app. I think AutoCAD WS web service should
    does as strong as RealDWG WCF web service. Or we can build a new .NET platform
    porting from RealDWG to work as a service. RealDWG is slow and single-threaded
    that is not suitable for cloud computing. I guess the back-end code of AutoCAD
    WS is Java as I got error messages from Apache server. AutoCAD WS should be the
    new “cloud RealDWG”.


    Khoa

    -----'
