comments:
- author: Maksim Sestic
  email: max@geoinova.com
  ip: 109.165.135.103
  url: http://www.geoinova.com
  date: '2013-08-14 21:07:27'
  body: Common use is "flattening out" building facades shot from a single or multiple
    angles (then glued together). Once facade is de-skewed and propely scaled, it
    may get digitized using AutoCAD (or simply used for measuring facade elements,
    like windows or openings).
- author: Eric Marantz
  email: ericm808@hotmail.com
  ip: 72.235.5.64
  url: ''
  date: '2013-08-14 22:14:17'
  body: "Something I sorely miss in AutoCad which MicroStation has,\nis a raster image\
    \ warping tool which maps a series of point pairs ie. image point to monument\
    \ point, etc...).\nIt's most typically useful tweeking skewed googleearth \nimages\
    \ to basemaps.\n\nI've faked it a few different ways in AutoCad. \nCreate a block\
    \ of the raster, and adjust xy scaling\nand then 3dRotate it if/as required to\
    \ 'fake' the eye.\n\nHard to believe that Autodesk has not implemented this \n\
    in AutoCAD."
- author: Brian Lockyear
  email: brian@slateshinglestudio.com
  ip: 72.11.112.171
  url: http://gnarlyarchitecture.com
  date: '2013-08-14 22:47:42'
  body: Shadow projections onto a planar surface.  3d modeling programs often do projection
    onto a plane but only along the plane normal.  If you want to project solar geometrically,
    as I did in Heliotrope, you have to project  obliquely from the sun.  Can still
    be done with a clever matrix operation.
- author: Gaston Nunez
  email: gaston.nunez@asyst.cl
  ip: 201.214.200.31
  url: ''
  date: '2013-08-15 01:44:27'
  body: "Hi, \n\nVery interesting, can you show the code used to de-skew the image?,as\
    \ for a suggestion, may be an implementation of the Hough transform to detect\
    \ features like the brackets of the matrix or some edges and then some angles\
    \ to de-skew or re project the image."
- author: Sean Tessier
  email: seant61@verizon.net
  ip: 96.238.36.122
  url: ''
  date: '2013-08-15 10:51:13'
  body: "I employ a similar technique with the Projective2d app.  Instead of the Matrix\
    \ manipulation, though, I used the ManagedARX IntersectWith function to contend\
    \ with all of the Linear Algebra.  Part of the reason for that was to facilitatetheo\
    \ processing necessary for projecting Splines with complete fidelity.\n\nWhat\
    \ may be surprising/interesting  – or maybe not  –  is that processing  Rational\
    \ Splines (Splines that have weighted CPs) is a Perspective (Projective) transform.\
    \   It’s a bit of a mind frack, as the 4d ControlPoint/Curve element requires\
    \ projection back to 3D space.  \n\nIt is nice to see the Autodesk developers\
    \ have provided enhanced functionality in this area of AutoCAD.  I will point\
    \ out, however, that the algorithm they used does not translate well to Grip manipulation.\n\
    \nIn the works, a local gallery intends to have numerous graphics applied to ceilings\
    \ floors and several wall oriented in non-orthographic angles.  At just one perspective\
    \ will all the graphics come together.  I had proposed the notion to them shortly\
    \ after the TTI Street Art blog."
- author: Mourad
  email: fezai_mourad@yahoo.fr
  ip: 41.226.11.78
  url: ''
  date: '2013-08-15 10:51:34'
  body: 'Hi Kean,


    This reminds me the question I''ve asked  about mapping google earth images (<a
    href="http://through-the-interface.typepad.com/through_the_interface/2009/04/triangulating-an-autocad-polyface-mesh-from-a-set-of-points-using-net.html).">http://through-the-interface.typepad.com/through_the_interface/2009/04/triangulating-an-autocad-polyface-mesh-from-a-set-of-points-using-net.html).</a>


    I so far could obtain a point cloud (X,Y,Z) with (X,Y) calculated using world
    file (<a href="http://en.wikipedia.org/wiki/World_file)">http://en.wikipedia.org/wiki/World_file)</a>
    georeferencing technique and Z calculated from a triangular mesh.


    The problem is that the code is too much slow, so I''ve only tested it with very
    small images (16 ko).


    I can send you the code (written in VB.Net) if you think this is interesting.


    Regards,


    Mourad'
- author: Kean Walmsley
  email: ''
  ip: 83.68.204.241
  url: http://profile.typepad.com/kean
  date: '2013-08-15 19:27:58'
  body: 'Will see what I can post... ideally in the context of AutoCAD.


    Kean'
- author: Kean Walmsley
  email: ''
  ip: 83.68.204.241
  url: http://profile.typepad.com/kean
  date: '2013-08-15 19:31:29'
  body: 'Hi Mourad,


    Ah yes, I remember. Colouring a point cloud seems a good way to go. It''s a shame
    it''s working so slowly for you.


    Feel free to send it over, but I can''t say when I''ll find time to take a look.


    Regards,


    Kean'
- author: Rod mertin
  email: rodmertin@hotmail.com
  ip: 136.153.18.101
  url: ''
  date: '2013-09-06 07:17:49'
  body: 'Hi Kean,

    Was reminded of this today when looking into interactive whiteboards for use in
    my first job as a firefighter.


    This technique could be used with a smartphone camera or similiar to live stream
    the contents of a normal whiteboard. The camera could be mounted to the top of
    the whiteboard similar to a short throw projector.


    Something like this would be incredibly useful and cost effective for us, and
    I think this would be useful to lots of other applications too.


    Regards Rod'
- author: Ruslan
  email: rustarg@gmail.com
  ip: 80.235.68.94
  url: ''
  date: '2013-09-20 06:14:21'
  body: "Hi Kean,\nIt's seems, that application above does linear transforms of the\
    \ picture. \nWhy you choosen python for such purposes? \nI'm working on alignment\
    \ situation plan stratening tool for Civil3D (aerial photos),and used WPF libraries\
    \ for image manipulations. Thats was quite enough for my purposes. \nAlso, I think,\
    \ there are many free c# libraries/wrappers for image processing.\n\nThank you\
    \ for your blog!"
- author: Kean Walmsley
  email: ''
  ip: 83.68.204.241
  url: http://profile.typepad.com/kean
  date: '2013-09-20 07:36:10'
  body: 'Hi Ruslan,


    I chose Python because the class I studied taught the technique in Python, and
    so I had Python code that implemented it. And it seemed an interesting challenge
    to have a single application with core capabilities in Python, UI in HTML/JavaScript
    and the glue in C#. It deals with some potentially interesting interop scenarios
    (getting data into the HTML page, getting data out of the HTML page into Python,
    getting the results out of Python into AutoCAD...).


    Would we write a core AutoCAD feature that does it this way? Almost certainly
    not. :-)


    Cheers,


    Kean'
- author: Ruslan
  email: rustarg@gmail.com
  ip: 80.235.103.98
  url: ''
  date: '2013-09-20 08:47:58'
  body: OK. It's really interesting to combine different technologies to get best
    of each one. Thank you for explanation.
- author: Chris
  email: kokenrei@gmail.com
  ip: 80.203.48.234
  url: ''
  date: '2013-09-25 21:28:16'
  body: "Hi Brian, \n\nAs i gathered, heliotrope projects shadows only on planar surfaces.\
    \ Is it possible to do so on non planar surfaces like a topography for example?"
- author: Bhaskar Rao
  email: bhaskarrao2k4@gmail.com
  ip: 14.99.201.223
  url: ''
  date: '2013-09-28 11:46:55'
  body: "Hi Kean,\n\nI am working with toposheets. Selected contours  are to be incorporated\
    \ in dwg file. \nIs it possible to capture RGB information of selected raster\
    \ pixels using VBA for autocad ?\n\nRegards\n\nBhaskar Rao"
- author: Kean Walmsley
  email: ''
  ip: 83.68.204.241
  url: http://profile.typepad.com/kean
  date: '2013-09-30 14:35:00'
  body: 'Hi Bhaskar,


    Perhaps, although with VBA it''d probably be trickier (it would be for me, anyway).


    I suggest posting your question to the relevant discussion group.


    Regards,


    Kean

    -----'
