comments:
- author: marco
  email: marco.maisto086@gmail.com
  ip: 151.100.122.236
  url: ''
  date: '2014-03-10 16:41:50'
  body: "Hi Kean, i'm sorry that i'm writing to you in this way but i don't know how\
    \ else can do it and don't know how to contact you in another way. \nAs you are\
    \ (in my opinion) really good in programming and creating plugin for autocad i\
    \ have a question realted to it: is it possible to write down a plugin in C++\
    \ and not in C#???\nI really need an answer to this question, and don't know whereelse\
    \ ask...\nso thank you in advance! :)"
- author: Kean Walmsley
  email: ''
  ip: 132.188.32.22
  url: http://profile.typepad.com/kean
  date: '2014-03-10 16:43:47'
  body: 'Hi Marco,


    The C++ plugin API for AutoCAD is known as ObjectARX.


    You will (for example) find lots of information about it on the AutoCAD Developer
    Center:


    <a href="http://autodesk.com/developautocad">http://autodesk.com/developautocad</a>


    I hope this helps,


    Kean

    -----'
