assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b019b01c7d462970d-500wi
  filename: image_9ac3df.jpg
  alt_text: Civil3D_Survey_Database
  title: Civil3D_Survey_Database
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b019b01c76bb3970b-500wi
  filename: image_0aced7.jpg
  alt_text: Civil3D_Survey_Database_Result
  title: Civil3D_Survey_Database_Result
  asset_type: image
