assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b0192abf990f9970d-500wi
  filename: image_88a09b.jpg
  alt_text: SettingsObjectLayerType
  title: SettingsObjectLayerType
  asset_type: image
