assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017c3671351e970b-pi
  filename: image_e8ed43.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017d409fb5e6970c-pi
  filename: image_c125a9.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017ee814773c970d-pi
  filename: image_85aab2.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017c36713752970b-pi
  filename: image_09a784.jpg
  alt_text: image
  title: image
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b017ee8147902970d-pi
  filename: image_0a8d26.jpg
  alt_text: image
  title: image
  asset_type: image
