assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01a73db44afd970d-pi
  filename: image_777d14.jpg
  alt_text: copylocal_false
  title: copylocal_false
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01a3fcf98b0c970b-pi
  filename: image_aa386f.jpg
  alt_text: debug_VS
  title: debug_VS
  asset_type: image
