assets:
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01a3fcdf1a80970b-500wi
  filename: image_e8d79d.jpg
  alt_text: Report_Settings_Civil3D
  title: Report_Settings_Civil3D
  asset_type: image
- url: https://adndevblog.typepad.com/.a/6a0167607c2431970b01a3fcdf1a85970b-500wi
  filename: image_68e12a.jpg
  alt_text: Drawing_Ambient_Settings
  title: Drawing_Ambient_Settings
  asset_type: image
