assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e1689788330120a4df3507970b-800wi
  filename: image_bec654.jpg
  alt_text: Electrical Settings
  title: Electrical Settings
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e1689788330120a5362bdd970c-800wi
  filename: image_c7cf87.jpg
  alt_text: DistributionSysType in RvtMgdDbg
  title: DistributionSysType in RvtMgdDbg
  asset_type: image
