assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e1689788330120a961a685970b-800wi
  filename: image_606fcb.jpg
  alt_text: ALL_MODEL_MARK parameter definition
  title: ALL_MODEL_MARK parameter definition
  asset_type: image
