assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e168978833014e8648558f970d-800wi
  filename: image_422122.jpg
  alt_text: External application required Regeneration option attribute
  title: External application required Regeneration option attribute
  asset_type: image
- url: http://thebuildingcoder.typepad.com/files/templaterevitarchaddincsjt4.zip
  filename: templaterevitarchaddincsjt4.zip
  alt_text: TemplateRevitArchAddinCsJt4.zip
  title: TemplateRevitArchAddinCsJt4.zip
  asset_type: file
