assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e168978833014e86d8b517970d-800wi
  filename: image_af18c0.jpg
  alt_text: Subset one endpoint
  title: Subset one endpoint
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e168978833014e5ffdd5d0970c-800wi
  filename: image_0ad438.jpg
  alt_text: Subset fully contained
  title: Subset fully contained
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e1689788330147e358977c970b-800wi
  filename: image_a9f510.jpg
  alt_text: Superset fully contained
  title: Superset fully contained
  asset_type: image
