assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e168978833017d42ef09fc970c-250wi
  filename: image_a118af.jpg
  alt_text: Upload from desktop to cloud and view on mobile device
  title: Upload from desktop to cloud and view on mobile device
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883301901b65ef3d970b-250wi
  filename: image_0937f1.jpg
  alt_text: Edit on mobile device, update data repository and BIM
  title: Edit on mobile device, update data repository and BIM
  asset_type: image
