assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e168978833019b00818516970d-300wi
  filename: image_3a4254.jpg
  alt_text: Room editor add-in user interface
  title: Room editor add-in user interface
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e168978833019b0083b610970c-250wi
  filename: image_f549df.jpg
  alt_text: Embedded icon resources
  title: Embedded icon resources
  asset_type: image
