assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883301a511605cf4970c-800wi
  filename: image_8cfa6f.jpg
  alt_text: Visibility settings
  title: Visibility settings
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883301a73d6bdd73970d-800wi
  filename: image_b55710.jpg
  alt_text: Visibility settings
  title: Visibility settings
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883301a511605d44970c-800wi
  filename: image_96f68e.jpg
  alt_text: Visibility settings
  title: Visibility settings
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883301a511605d64970c-800wi
  filename: image_d6ba41.jpg
  alt_text: Visibility settings
  title: Visibility settings
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883301a73d6bdd10970d-400wi
  filename: image_cd68fa.jpg
  alt_text: Happy Year of the Horse!
  title: Happy Year of the Horse!
  asset_type: image
