assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883301b7c7c0711c970b-800wi
  filename: image_aa3d0e.jpg
  alt_text: Popular programming languages 2015
  title: Popular programming languages 2015
  asset_type: image
