assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883301b8d135db04970c-150wi
  filename: image_526b16.jpg
  alt_text: GitHub contributions
  title: GitHub contributions
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883301b8d135d680970c-500wi
  filename: image_afcf96.jpg
  alt_text: Grevit
  title: Grevit
  asset_type: image
