assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883301b7c7ef189e970b-800wi
  filename: image_6d8df1.jpg
  alt_text: Drop-down parameter enum combo
  title: Drop-down parameter enum combo
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883301bb089339a0970d-800wi
  filename: image_ffbd7c.jpg
  alt_text: Drop-down parameter enum combo
  title: Drop-down parameter enum combo
  asset_type: image
