assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883301b7c9046b5a970b-250wi
  filename: image_ad2d60.jpg
  alt_text: Astar progress animation
  title: Astar progress animation
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883301b7c9046b66970b-800wi
  filename: image_8c7442.jpg
  alt_text: Possible ElementId parameter values
  title: Possible ElementId parameter values
  asset_type: image
