assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883301bb0a02ec2e970d-800wi
  filename: image_5d51d1.jpg
  alt_text: About Revit 2018.3
  title: About Revit 2018.3
  asset_type: image
