assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e1689788330224e03a5ad2200d-800wi
  filename: image_e5ec76.jpg
  alt_text: Forge meta property editor
  title: Forge meta property editor
  asset_type: image
