assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e1689788330240a45c12d2200c-400wi
  filename: image_134954.jpg
  alt_text: Rapid application development
  title: Rapid application development
  asset_type: image
