assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e1689788330240a4d41204200d-400wi
  filename: image_0796fc.jpg
  alt_text: FindInserts
  title: FindInserts
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e1689788330240a4f8b5fe200b-800wi
  filename: image_43b38d.jpg
  alt_text: Wall shadow cutout
  title: Wall shadow cutout
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e1689788330240a4d4120b200d-800wi
  filename: image_aa7dc9.jpg
  alt_text: FindInserts demo
  title: FindInserts demo
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e1689788330240a4aaed10200c-400wi
  filename: image_ae4d7d.jpg
  alt_text: ExportWaypointsJson ribbon panel
  title: ExportWaypointsJson ribbon panel
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e1689788330240a4f8b616200b-150wi
  filename: image_5070ee.jpg
  alt_text: ExportWaypointsJson main command and settings buttons
  title: ExportWaypointsJson main command and settings buttons
  asset_type: image
