assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e1689788330263e96e10fe200b-800wi
  filename: image_f9262e.jpg
  alt_text: Camera parameters before zooming and panning
  title: Camera parameters before zooming and panning
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e168978833026bde9b67b7200c-800wi
  filename: image_2a0125.jpg
  alt_text: Camera parameters after zooming and panning
  title: Camera parameters after zooming and panning
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e168978833026bde9b67c0200c-800wi
  filename: image_b46f08.jpg
  alt_text: Scale calculation
  title: Scale calculation
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e168978833026bde9b67cb200c-800wi
  filename: image_3346bc.jpg
  alt_text: Zooming corners
  title: Zooming corners
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e168978833026bde9b67a6200c-800wi
  filename: image_f5f528.jpg
  alt_text: Keynote file cheat sheet
  title: Keynote file cheat sheet
  asset_type: image
