assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883302c8d3ae4291200d-800wi
  filename: image_3adab9.jpg
  alt_text: Path of travel doors
  title: Path of travel doors
  asset_type: image
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883302c8d3aa225c200c-800wi
  filename: image_f87ee2.jpg
  alt_text: APS perspective view camera
  title: APS perspective view camera
  asset_type: image
