assets:
- url: https://thebuildingcoder.typepad.com/.a/6a00e553e16897883302c8d3cd83b6200c-800wi
  filename: image_fe7056.jpg
  alt_text: GetBboxElementOnSheet
  title: GetBboxElementOnSheet
  asset_type: image
